module.exports = {
    "AC":{
       "shortName":"AC",
       "longName":"Asiacoin",
       "network":{
          "messagePrefix":"\u0018AsiaCoin Signed Message:\n",
          "bip32":{
             "public":76067358,
             "private":76066276
          },
          "pubKeyHash":23,
          "scriptHash":8,
          "wif":151
       },
       "coinNumber":51
    },
    "ACC":{
       "shortName":"ACC",
       "longName":"Adcoin",
       "network":{
          "messagePrefix":"\u0018AdCoin Signed Message:\n",
          "bip32":{
             "public":76067358,
             "private":76066276
          },
          "pubKeyHash":23,
          "scriptHash":5,
          "wif":176
       },
       "coinNumber":161
    },
    "AGM":{
       "shortName":"AGM",
       "longName":"Argoneum",
       "network":{
          "messagePrefix":"unused",
          "bip32":{
             "public":76067358,
             "private":76066276
          },
          "pubKeyHash":50,
          "scriptHash":97,
          "wif":191
       },
       "coinNumber":421
    },
    "ARYA":{
       "shortName":"ARYA",
       "longName":"Aryacoin",
       "network":{
          "messagePrefix":"\u0018Aryacoin Signed Message:\n",
          "bech32":"arya",
          "bip32":{
             "public":76067358,
             "private":76066276
          },
          "pubKeyHash":23,
          "scriptHash":111,
          "wif":151
       },
       "coinNumber":357
    },
    "AUR":{
       "shortName":"AUR",
       "longName":"Auroracoin",
       "network":{
          "messagePrefix":"\u0018AuroraCoin Signed Message:\n",
          "bip32":{
             "public":76067358,
             "private":76066276
          },
          "pubKeyHash":23,
          "scriptHash":5,
          "wif":151
       },
       "coinNumber":85
    },
    "AXE":{
       "shortName":"AXE",
       "longName":"Axe",
       "network":{
          "messagePrefix":"unused",
          "bip32":{
             "public":76067358,
             "private":76066276
          },
          "pubKeyHash":55,
          "scriptHash":16,
          "wif":204
       },
       "coinNumber":4242
    },
    "ANON":{
       "shortName":"ANON",
       "longName":"ANON",
       "network":{
          "messagePrefix":"\u0018ANON Signed Message:\n",
          "bip32":{
             "public":76067358,
             "private":76066276
          },
          "pubKeyHash":1410,
          "scriptHash":21385,
          "wif":128
       },
       "coinNumber":220
    },
    "BOLI":{
       "shortName":"BOLI",
       "longName":"Bolivarcoin",
       "network":{
          "messagePrefix":"Bolivarcoin Signed Message:\n",
          "bip32":{
             "public":76067358,
             "private":76066276
          },
          "pubKeyHash":85,
          "scriptHash":5,
          "wif":213
       },
       "coinNumber":278
    },
    "BCA":{
       "shortName":"BCA",
       "longName":"Bitcoin Atom",
       "network":{
          "messagePrefix":"\u0018Bitcoin Signed Message:\n",
          "bip32":{
             "public":76067358,
             "private":76066276
          },
          "pubKeyHash":23,
          "scriptHash":10,
          "wif":128,
          "p2wpkh":{
            "baseNetwork":"atom",
            "messagePrefix":"\\x18Bitcoin Atom Signed Message:\n",
            "bech32":"atom",
            "bip32":{
               "public":0x0488B21E,
               "private":0x0488ADE4
            },
            "pubKeyHash":0x17,
            "scriptHash":0x0a,
            "wif":0x80
         },
         "p2wpkhInP2sh":{
            "baseNetwork":"atom",
            "messagePrefix":"\\x18Bitcoin Atom Signed Message:\n",
            "bech32":"atom",
            "bip32":{
               "public":0x0488B21E,
               "private":0x0488ADE4
            },
            "pubKeyHash":0x17,
            "scriptHash":0x0a,
            "wif":0x80
         }
       },
       "coinNumber":185
    },
    "BCH":{
       "shortName":"BCH",
       "longName":"Bitcoin Cash",
       "network":"dummyNetwork",
       "coinNumber":145
    },
    "BEET":{
       "shortName":"BEET",
       "longName":"Beetlecoin",
       "network":{
          "messagePrefix":"\u0019Beetlecoin Signed Message:\n",
          "bip32":{
             "public":76067358,
             "private":76066276
          },
          "pubKeyHash":26,
          "scriptHash":85,
          "wif":153
       },
       "coinNumber":800
    },
    "BELA":{
       "shortName":"BELA",
       "longName":"Belacoin",
       "network":{
          "messagePrefix":"\u0018BelaCoin Signed Message:\n",
          "bip32":{
             "public":76067358,
             "private":76066276
          },
          "pubKeyHash":25,
          "scriptHash":5,
          "wif":153
       },
       "coinNumber":73
    },
    "BLK":{
       "shortName":"BLK",
       "longName":"BlackCoin",
       "network":{
          "messagePrefix":"\u0018BlackCoin Signed Message:\n",
          "bip32":{
             "public":47169246,
             "private":47169376
          },
          "pubKeyHash":25,
          "scriptHash":85,
          "wif":153
       },
       "coinNumber":10
    },
    "BND":{
       "shortName":"BND",
       "longName":"Blocknode",
       "network":{
          "messagePrefix":"\u0018Blocknode Signed Message:\n",
          "bip32":{
             "public":76067358,
             "private":76066276
          },
          "pubKeyHash":25,
          "scriptHash":63,
          "wif":75
       },
       "coinNumber":2941
    },
    "tBND":{
       "shortName":"tBND",
       "longName":"Blocknode Testnet",
       "network":{
          "messagePrefix":"\u0018Blocknode Testnet Signed Message:\n",
          "bip32":{
             "public":70617039,
             "private":70615956
          },
          "pubKeyHash":85,
          "scriptHash":125,
          "wif":137
       },
       "coinNumber":1
    },
    "BRIT":{
       "shortName":"BRIT",
       "longName":"Britcoin",
       "network":{
          "messagePrefix":"\u0018BritCoin Signed Message:\n",
          "bip32":{
             "public":76067358,
             "private":76066276
          },
          "pubKeyHash":25,
          "scriptHash":85,
          "wif":153
       },
       "coinNumber":70
    },
    "BSD":{
       "shortName":"BSD",
       "longName":"Bitsend",
       "network":{
          "messagePrefix":"\u0018Bitsend Signed Message:\n",
          "bip32":{
             "public":76067358,
             "private":76066276
          },
          "pubKeyHash":102,
          "scriptHash":5,
          "wif":204
       },
       "coinNumber":91
    },
    "BST":{
       "shortName":"BST",
       "longName":"BlockStamp",
       "network":{
          "messagePrefix":"\u0018BlockStamp Signed Message:\n",
          "bip32":{
             "public":76067358,
             "private":76066276
          },
          "pubKeyHash":0,
          "scriptHash":5,
          "wif":128,
          "p2wpkh":{
            "baseNetwork":"blockstamp",
            "messagePrefix":"\\x18BlockStamp Signed Message:\n",
            "bech32":"bc",
            "bip32":{
               "public":0x0488B21E,
               "private":0x0488ADE4
            },
            "pubKeyHash":0x00,
            "scriptHash":0x05,
            "wif":0x80
         },
         "p2wpkhInP2sh":{
            "baseNetwork":"blockstamp",
            "messagePrefix":"\\x18BlockStamp Signed Message:\n",
            "bech32":"bc",
            "bip32":{
               "public":0x0488B21E,
               "private":0x0488ADE4
            },
            "pubKeyHash":0x00,
            "scriptHash":0x05,
            "wif":0x80
         }
       },
       "coinNumber":254
    },
    "BTA":{
       "shortName":"BTA",
       "longName":"Bata",
       "network":{
          "messagePrefix":"\u0018Bata Signed Message:\n",
          "bip32":{
             "public":2752284410,
             "private":2752221629
          },
          "pubKeyHash":25,
          "scriptHash":5,
          "wif":164
       },
       "coinNumber":89
    },
    "BTC":{
       "shortName":"BTC",
       "longName":"Bitcoin",
       "network":{
        "messagePrefix": '\u0018Bitcoin Signed Message:\n',
        "bech32": 'bc',
        "bip32": { 
            "public": 76067358, 
            "private": 76066276 
        },
        "pubKeyHash": 0,
        "scriptHash": 5,
        "wif": 128,
        "p2wpkh":{
            "baseNetwork":"bitcoin",
            "messagePrefix":"\\x18Bitcoin Signed Message:\n",
            "bech32":"bc",
            "bip32":{
                  "public":0x04b24746,
                  "private":0x04b2430c
               },
            "pubKeyHash":0x00,
            "scriptHash":0x05,
            "wif":0x80
         },
         "p2wpkhInP2sh":{
            "baseNetwork":"bitcoin",
            "messagePrefix":"\\x18Bitcoin Signed Message:\n",
            "bech32":"bc",
            "bip32":{
               "public":0x049d7cb2,
               "private":0x049d7878
            },
            "pubKeyHash":0x00,
            "scriptHash":0x05,
            "wif":0x80
         },
         "p2wsh":{
            "baseNetwork":"bitcoin",
            "messagePrefix":"\\x18Bitcoin Signed Message:\n",
            "bech32":"bc",
            "bip32":{
               "public":0x02aa7ed3,
               "private":0x02aa7a99
            },
            "pubKeyHash":0x00,
            "scriptHash":0x05,
            "wif":0x80
         },
         "p2wshInP2sh":{
            "baseNetwork":"bitcoin",
            "messagePrefix":"\\x18Bitcoin Signed Message:\n",
            "bech32":"bc",
            "bip32":{
               "public":0x0295b43f,
               "private":0x0295b005
            },
            "pubKeyHash":0x00,
            "scriptHash":0x05,
            "wif":0x80
         }
      },
      "coinNumber":0
    },
    "BTCt":{
        "shortName":"BTCt",
        "longName":"Bitcoin Testnet",
        "network":{
            "messagePrefix": '\u0018Bitcoin Signed Message:\n',
            "bech32": 'tb',
            "bip32": { 
                "public": 70617039, 
                "private": 70615956 
            },
            "pubKeyHash": 111,
            "scriptHash": 196,
            "wif": 239,
            "p2wpkh":{
               "baseNetwork":"testnet",
               "messagePrefix":"\\x18Bitcoin Signed Message:\n",
               "bech32":"tb",
               "bip32":{
                  "public":0x045f1cf6,
                  "private":0x045f18bc
               },
               "pubKeyHash":0x6f,
               "scriptHash":0xc4,
               "wif":0xef
            },
            "p2wpkhInP2sh":{
               "baseNetwork":"testnet",
               "messagePrefix":"\\x18Bitcoin Signed Message:\n",
               bech32:"tb",
               bip32:{
                  "public":0x044a5262,
                  "private":0x044a4e28
               },
               "pubKeyHash":0x6f,
               "scriptHash":0xc4,
               "wif":0xef
            },
            "p2wsh":{
               "baseNetwork":"testnet",
               "messagePrefix":"\\x18Bitcoin Signed Message:\n",
               "bech32":"tb",
               "bip32":{
                  "public":0x02575483,
                  "private":0x02575048
               },
               "pubKeyHash":0x6f,
               "scriptHash":0xc4,
               "wif":0xef
            },
            "p2wshInP2sh":{
               "baseNetwork":"testnet",
               "messagePrefix":"\\x18Bitcoin Signed Message:\n",
               "bech32":"tb",
               "bip32":{
                  "public":0x024289ef,
                  "private":0x024285b5
               },
               "pubKeyHash":0x6f,
               "scriptHash":0xc4,
               "wif":0xef
            }
          },
        "coinNumber":1
    },
    "BTCrt":{
        "shortName":"BTCrt",
        "longName":"Bitcoin RegTest",
        "network":{
            "messagePrefix": '\u0018Bitcoin Signed Message:\n',
            "bech32": 'bcrt',
            "bip32": { 
                "public": 70617039, 
                "private": 70615956 
            },
            "pubKeyHash": 111,
            "scriptHash": 196,
            "wif": 239,
            "p2wpkh":{
               "baseNetwork":"regtest",
               "messagePrefix":"\\x18Bitcoin Signed Message:\n",
               "bech32":"bcrt",
               "bip32":{
                  "public":0x045f1cf6,
                  "private":0x045f18bc
               },
               "pubKeyHash":0x6f,
               "scriptHash":0xc4,
               "wif":0xef
            },
            "p2wpkhInP2sh":{
               "baseNetwork":"regtest",
               "messagePrefix":"\\x18Bitcoin Signed Message:\n",
               "bech32":"bcrt",
               "bip32":{
                  "public":0x044a5262,
                  "private":0x044a4e28
               },
               "pubKeyHash":0x6f,
               "scriptHash":0xc4,
               "wif":0xef
            },
            "p2wsh":{
               "baseNetwork":"regtest",
               "messagePrefix":"\\x18Bitcoin Signed Message:\n",
               "bech32":"bcrt",
               "bip32":{
                  "public":0x02575483,
                  "private":0x02575048
               },
               "pubKeyHash":0x6f,
               "scriptHash":0xc4,
               "wif":0xef
            },
            "p2wshInP2sh":{
               "baseNetwork":"regtest",
               "messagePrefix":"\\x18Bitcoin Signed Message:\n",
               "bech32":"bcrt",
               "bip32":{
                  "public":0x024289ef,
                  "private":0x024285b5
               },
               "pubKeyHash":0x6f,
               "scriptHash":0xc4,
               "wif":0xef
            }
        },
        "coinNumber":1
    },
    "BITG":{
       "shortName":"BITG",
       "longName":"Bitcoin Green",
       "network":{
          "messagePrefix":"\u0018BitcoinGreen Signed Message:\n",
          "bip32":{
             "public":76067358,
             "private":76066276
          },
          "pubKeyHash":38,
          "scriptHash":7357,
          "wif":46
       },
       "coinNumber":222
    },
    "BTCP":{
       "shortName":"BTCP",
       "longName":"Bitcoin Private",
       "network":{
          "messagePrefix":"\u0018BitcoinPrivate Signed Message:\n",
          "bip32":{
             "public":76067358,
             "private":76066276
          },
          "pubKeyHash":4901,
          "scriptHash":5039,
          "wif":128
       },
       "coinNumber":183
    },
    "BSC":{
       "shortName":"BSC",
       "longName":"Binance Smart Chain",
       "network":{
          "messagePrefix":"\u0018Bitcoin Signed Message:\n",
          "bech32":"bc",
          "bip32":{
             "public":76067358,
             "private":76066276
          },
          "pubKeyHash":0,
          "scriptHash":5,
          "wif":128
       },
       "coinNumber":60
    },
    "BSV":{
       "shortName":"BSV",
       "longName":"BitcoinSV",
       "network":{
          "messagePrefix":"unused",
          "bip32":{
             "public":76067358,
             "private":76066276
          },
          "pubKeyHash":0,
          "scriptHash":5,
          "wif":128
       },
       "coinNumber":236
    },
    "BTCZ":{
       "shortName":"BTCZ",
       "longName":"Bitcoinz",
       "network":{
          "messagePrefix":"\u0018BitcoinZ Signed Message:\n",
          "bip32":{
             "public":76067358,
             "private":76066276
          },
          "pubKeyHash":7352,
          "scriptHash":7357,
          "wif":128
       },
       "coinNumber":177
    },
    "BTDX":{
       "shortName":"BTDX",
       "longName":"BitCloud",
       "network":{
          "messagePrefix":"\u0018BitCloud Signed Message:\n",
          "bip32":{
             "public":76067358,
             "private":76066276
          },
          "pubKeyHash":25,
          "scriptHash":5,
          "wif":153
       },
       "coinNumber":218
    },
    "BTG":{
       "shortName":"BTG",
       "longName":"Bitcoin Gold",
       "network":{
          "messagePrefix":"\u001dBitcoin Gold Signed Message:\n",
          "bip32":{
             "public":76067358,
             "private":76066276
          },
          "pubKeyHash":38,
          "scriptHash":23,
          "wif":128,
          "p2wpkh":{
            "baseNetwork":"bgold",
            "messagePrefix":"\\x1DBitcoin Gold Signed Message:\n",
            "bech32":"btg",
            "bip32":{
               "public":0x04b24746,
               "private":0x04b2430c
            },
            "pubKeyHash":0x26,
            "scriptHash":0x17,
            "wif":0x80
         },
         "p2wpkhInP2sh":{
            "baseNetwork":"bgold",
            "messagePrefix":"\\x1DBitcoin Gold Signed Message:\n",
            "bech32":"btg",
            "bip32":{
               "public":0x049d7cb2,
               "private":0x049d7878
            },
            "pubKeyHash":0x26,
            "scriptHash":0x17,
            "wif":0x80
         }
       },
       "coinNumber":156
    },
    "BTX":{
       "shortName":"BTX",
       "longName":"Bitcore",
       "network":{
          "messagePrefix":"\u0018BitCore Signed Message:\n",
          "bip32":{
             "public":76067358,
             "private":76066276
          },
          "pubKeyHash":3,
          "scriptHash":125,
          "wif":128,
          "p2wpkh":{
            "baseNetwork":"bitcore",
            "messagePrefix":"\\x18BitCore Signed Message:\n",
            "bech32":"bitcore",
            "bip32":{
               "public":0x0488B21E,
               "private":0x0488ADE4
            },
            "pubKeyHash":0x03,
            "scriptHash":0x7D,
            "wif":0x80
         },
         "p2wpkhInP2sh":{
            "baseNetwork":"bitcore",
            "messagePrefix":"\\x18BitCore Signed Message:\n",
            "bech32":"bitcore",
            "bip32":{
               "public":0x0488B21E,
               "private":0x0488ADE4
            },
            "pubKeyHash":0x03,
            "scriptHash":0x7D,
            "wif":0x80
         }
       },
       "coinNumber":160
    },
    "CCN":{
       "shortName":"CCN",
       "longName":"Cannacoin",
       "network":{
          "messagePrefix":"\u0018Cannacoin Signed Message:\n",
          "bip32":{
             "public":76067358,
             "private":76066276
          },
          "pubKeyHash":28,
          "scriptHash":5,
          "wif":156
       },
       "coinNumber":19
    },
    "CESC":{
       "shortName":"CESC",
       "longName":"Cryptoescudo",
       "network":{
          "messagePrefix":"\u0018Cannacoin Signed Message:\n",
          "bip32":{
             "public":76067358,
             "private":76066276
          },
          "pubKeyHash":28,
          "scriptHash":5,
          "wif":156
       },
       "coinNumber":111
    },
    "CDN":{
       "shortName":"CDN",
       "longName":"Canadaecoin",
       "network":{
          "messagePrefix":"\u0018Canada eCoin Signed Message:\n",
          "bip32":{
             "public":76067358,
             "private":76066276
          },
          "pubKeyHash":28,
          "scriptHash":5,
          "wif":156
       },
       "coinNumber":34
    },
    "CLAM":{
       "shortName":"CLAM",
       "longName":"Clams",
       "network":{
          "messagePrefix":"unused",
          "bip32":{
             "public":2831314276,
             "private":2831251494
          },
          "pubKeyHash":137,
          "scriptHash":13,
          "wif":133
       },
       "coinNumber":23
    },
    "CLO":{
       "shortName":"CLO",
       "longName":"Callisto",
       "segwitAvailable":false,
       "network":{
          "messagePrefix":"\u0018Bitcoin Signed Message:\n",
          "bech32":"bc",
          "bip32":{
             "public":76067358,
             "private":76066276
          },
          "pubKeyHash":0,
          "scriptHash":5,
          "wif":128
       },
       "coinNumber":820
    },
    "CLUB":{
       "shortName":"CLUB",
       "longName":"Clubcoin",
       "network":{
          "messagePrefix":"\u0018ClubCoin Signed Message:\n",
          "bip32":{
             "public":76067358,
             "private":76066276
          },
          "pubKeyHash":28,
          "scriptHash":85,
          "wif":153
       },
       "coinNumber":79
    },
    "CMP":{
       "shortName":"CMP",
       "longName":"Compcoin",
       "network":{
          "messagePrefix":"\u0018CompCoin Signed Message:\n",
          "bip32":{
             "public":76067358,
             "private":76066276
          },
          "pubKeyHash":28,
          "scriptHash":85,
          "wif":156
       },
       "coinNumber":71
    },
    "CPU":{
       "shortName":"CPU",
       "longName":"CPUchain",
       "network":{
          "messagePrefix":"x18CPUchain Signed Message:\n",
          "bip32":{
             "public":76067358,
             "private":76066276
          },
          "pubKeyHash":28,
          "scriptHash":30,
          "wif":128,
          "p2wpkh":{
            "baseNetwork":"cpuchain",
            "messagePrefix":"\\x1DCPUchain Signed Message:\n",
            "bech32":"cpu",
            "bip32":{
               "public":0x04b24746,
               "private":0x04b2430c
            },
            "pubKeyHash":0x1c,
            "scriptHash":0x1e,
            "wif":0x80
         },
         "p2wpkhInP2sh":{
            "baseNetwork":"cpuchain",
            "messagePrefix":"\\x1DCPUchain Signed Message:\n",
            "bech32":"cpu",
            "bip32":{
               "public":0x049d7cb2,
               "private":0x049d7878
            },
            "pubKeyHash":0x1c,
            "scriptHash":0x1e,
            "wif":0x80
         }
       },
       "coinNumber":363
    },
    "CRAVE":{
       "shortName":"CRAVE",
       "longName":"Crave",
       "network":{
          "messagePrefix":"\u0018DarkNet Signed Message:\n",
          "bip32":{
             "public":76067358,
             "private":76066276
          },
          "pubKeyHash":70,
          "scriptHash":85,
          "wif":153
       },
       "coinNumber":186
    },
    "CRP":{
       "shortName":"CRP",
       "longName":"CranePay",
       "network":{
          "messagePrefix":"\u0018Bitcoin Signed Message:\n",
          "bip32":{
             "public":76067358,
             "private":76066276
          },
          "pubKeyHash":28,
          "scriptHash":10,
          "wif":123,
          "p2wpkhInP2sh":{
            "baseNetwork":"cranepay",
            "messagePrefix":"\\x18Bitcoin Signed Message:\n",
            "bech32":"cp",
            "bip32":{
               "public":0x049d7cb2,
               "private":0x049d7878
            },
            "pubKeyHash":28,
            "scriptHash":10,
            "wif":123
         },
         "p2wpk":{
            "baseNetwork":"cranepay",
            "messagePrefix":"\\x18Bitcoin Signed Message:\n",
            "bech32":"cp",
            "bip32":{
               "public":0x04b24746,
               "private":0x04b2430c
            },
            "pubKeyHash":28,
            "scriptHash":10,
            "wif":123
         }
       },
       "coinNumber":2304
    },
    "CRW":{
       "shortName":"CRW",
       "longName":"Crown",
       "network":"crown",
       "coinNumber":72
    },
    "CSC":{
       "shortName":"CSC",
       "longName":"CasinoCoin",
       "network":{
          "messagePrefix":"\u0018Bitcoin Signed Message:\n",
          "bech32":"bc",
          "bip32":{
             "public":76067358,
             "private":76066276
          },
          "pubKeyHash":0,
          "scriptHash":5,
          "wif":128
       },
       "coinNumber":359
    },
    "DASH":{
       "shortName":"DASH",
       "longName":"Dash",
       "network":{
        "messagePrefix": 'unused',
        "bip32": {
          "public": 0x0488b21e,
          "private": 0x0488ade4
        },
        "pubKeyHash": 0x4c,
        "scriptHash": 0x10,
        "wif": 0xcc
      },
       "coinNumber":5
    },
    "DASHt":{
        "shortName":"DASHt",
        "longName":"Dash Testnet",
        "network":{
           "messagePrefix":"unused",
           "bip32":{
              "public":70617039,
              "private":70615956
           },
           "pubKeyHash":140,
           "scriptHash":19,
           "wif":239
        },
        "coinNumber":1
     },
    "DFC":{
       "shortName":"DFC",
       "longName":"Defcoin",
       "network":{
          "messagePrefix":"\u0018defcoin Signed Message:\n",
          "bip32":{
             "public":76067358,
             "private":76066276
          },
          "pubKeyHash":30,
          "scriptHash":5,
          "wif":158
       },
       "coinNumber":1337
    },
    "DGB":{
       "shortName":"DGB",
       "longName":"Digibyte",
       "network":{
          "messagePrefix":"\u0019DigiByte Signed Message:\n",
          "bip32":{
             "public":76067358,
             "private":76066276
          },
          "pubKeyHash":30,
          "scriptHash":5,
          "wif":128,
          "p2wpkh":{
            "baseNetwork":"digibyte",
            "messagePrefix":"x19DigiByte Signed Message:\n",
            "bech32":"dgb",
            "bip32":{
               "public":0x04b24746,
               "private":0x04b2430c
            },
            "pubKeyHash":0x1e,
            "scriptHash":0x3f,
            "wif":0x80
         },
         "p2wpkhInP2sh":{
            "baseNetwork":"digibyte",
            "messagePrefix":"\\x19DigiByte Signed Message:\n",
            "bech32":"dgb",
            "bip32":{
               "public":0x049d7cb2,
               "private":0x049d7878
            },
            "pubKeyHash":0x1e,
            "scriptHash":0x3f,
            "wif":0x80
         }
       },
       "coinNumber":20
    },
    "DGC":{
       "shortName":"DGC",
       "longName":"Digitalcoin",
       "network":{
          "messagePrefix":"\u0018Digitalcoin Signed Message:\n",
          "bip32":{
             "public":2651097266,
             "private":76066276
          },
          "pubKeyHash":30,
          "scriptHash":5,
          "wif":158
       },
       "coinNumber":18
    },
    "DMD":{
       "shortName":"DMD",
       "longName":"Diamond",
       "network":{
          "messagePrefix":"\u0018Diamond Signed Message:\n",
          "bip32":{
             "public":76067358,
             "private":76066276
          },
          "pubKeyHash":90,
          "scriptHash":8,
          "wif":218
       },
       "coinNumber":152
    },
    "DNR":{
       "shortName":"DNR",
       "longName":"Denarius",
       "network":{
          "messagePrefix":"\u0019Denarius Signed Message:\n",
          "bip32":{
             "public":76067358,
             "private":76066276
          },
          "pubKeyHash":30,
          "scriptHash":90,
          "wif":158
       },
       "coinNumber":116
    },
    "DOGE":{
       "shortName":"DOGE",
       "longName":"Dogecoin",
       "network":{
          "messagePrefix":"\u0019Dogecoin Signed Message:\n",
          "bip32":{
             "public":49990397,
             "private":49988504
          },
          "pubKeyHash":30,
          "scriptHash":22,
          "wif":158
       },
       "coinNumber":3
    },
    "DOGEt":{
       "shortName":"DOGEt",
       "longName":"Dogecoin Testnet",
       "network":{
          "messagePrefix":"\u0019Dogecoin Signed Message:\n",
          "bip32":{
             "public":70617039,
             "private":70615956
          },
          "pubKeyHash":113,
          "scriptHash":196,
          "wif":241,
          "p2wpkh":{
            "baseNetwork":"dogecointestnet",
            "messagePrefix":"\\x19Dogecoin Signed Message:\n",
            "bech32":"dogecointestnet",
            "bip32":{
               "public":0x043587cf,
               "private":0x04358394
            },
            "pubKeyHash":0x71,
            "scriptHash":0xc4,
            "wif":0xf1
         },
         "p2wpkhInP2sh":{
            "baseNetwork":"dogecointestnet",
            "messagePrefix":"\\x19Dogecoin Signed Message:\n",
            "bech32":"dogecointestnet",
            "bip32":{
               "public":0x043587cf,
               "private":0x04358394
            },
            "pubKeyHash":0x71,
            "scriptHash":0xc4,
            "wif":0xf1
         }
       },
       "coinNumber":1
    },
    "DXN":{
       "shortName":"DXN",
       "longName":"DEXON",
       "network":{
          "messagePrefix":"\u0018Bitcoin Signed Message:\n",
          "bech32":"bc",
          "bip32":{
             "public":76067358,
             "private":76066276
          },
          "pubKeyHash":0,
          "scriptHash":5,
          "wif":128
       },
       "coinNumber":237
    },
    "ECN":{
       "shortName":"ECN",
       "longName":"Ecoin",
       "network":{
          "messagePrefix":"\u0018eCoin Signed Message:\n",
          "bip32":{
             "public":76067358,
             "private":76066276
          },
          "pubKeyHash":92,
          "scriptHash":20,
          "wif":220
       },
       "coinNumber":115
    },
    "EDRC":{
       "shortName":"EDRC",
       "longName":"Edrcoin",
       "network":{
          "messagePrefix":"\u0018EDRcoin Signed Message:\n",
          "bip32":{
             "public":76067358,
             "private":76066276
          },
          "pubKeyHash":93,
          "scriptHash":28,
          "wif":221
       },
       "coinNumber":56
    },
    "EFL":{
       "shortName":"EFL",
       "longName":"Egulden",
       "network":{
          "messagePrefix":"\u0018Egulden Signed Message:\n",
          "bip32":{
             "public":76067358,
             "private":76066276
          },
          "pubKeyHash":48,
          "scriptHash":5,
          "wif":176
       },
       "coinNumber":78
    },
    "ELA":{
       "shortName":"ELA",
       "longName":"Elastos",
       "network":{
          "messagePrefix":"unused",
          "bip32":{
             "public":76067358,
             "private":76066276
          },
          "pubKeyHash":33,
          "scriptHash":196,
          "wif":239
       },
       "coinNumber":2305
    },
    "ELLA":{
       "shortName":"ELLA",
       "longName":"Ellaism",
       "segwitAvailable":false,
       "network":{
          "messagePrefix":"\u0018Bitcoin Signed Message:\n",
          "bech32":"bc",
          "bip32":{
             "public":76067358,
             "private":76066276
          },
          "pubKeyHash":0,
          "scriptHash":5,
          "wif":128
       },
       "coinNumber":163
    },
    "EMC2":{
       "shortName":"EMC2",
       "longName":"Einsteinium",
       "network":{
          "messagePrefix":"\u0018Einsteinium Signed Message:\n",
          "bip32":{
             "public":76067358,
             "private":76066276
          },
          "pubKeyHash":33,
          "scriptHash":5,
          "wif":161
       },
       "coinNumber":41
    },
    "ERC":{
       "shortName":"ERC",
       "longName":"Europecoin",
       "network":{
          "messagePrefix":"\u0018Bitcoin Signed Message:\n",
          "bip32":{
             "public":76067358,
             "private":76066276
          },
          "pubKeyHash":33,
          "scriptHash":5,
          "wif":168
       },
       "coinNumber":151
    },
    "EOS":{
       "shortName":"EOS",
       "longName":"EOSIO",
       "network":{
          "messagePrefix":"\u0018Bitcoin Signed Message:\n",
          "bech32":"bc",
          "bip32":{
             "public":76067358,
             "private":76066276
          },
          "pubKeyHash":0,
          "scriptHash":5,
          "wif":128
       },
       "coinNumber":194
    },
    "ERE":{
       "shortName":"ERE",
       "longName":"EtherCore",
       "segwitAvailable":false,
       "network":{
          "messagePrefix":"\u0018Bitcoin Signed Message:\n",
          "bech32":"bc",
          "bip32":{
             "public":76067358,
             "private":76066276
          },
          "pubKeyHash":0,
          "scriptHash":5,
          "wif":128
       },
       "coinNumber":466
    },
    "ESN":{
       "shortName":"ESN",
       "longName":"Ethersocial Network",
       "segwitAvailable":false,
       "network":{
          "messagePrefix":"\u0018Bitcoin Signed Message:\n",
          "bech32":"bc",
          "bip32":{
             "public":76067358,
             "private":76066276
          },
          "pubKeyHash":0,
          "scriptHash":5,
          "wif":128
       },
       "coinNumber":31102
    },
    "ETC":{
       "shortName":"ETC",
       "longName":"Ethereum Classic",
       "segwitAvailable":false,
       "network":{
          "messagePrefix":"\u0018Bitcoin Signed Message:\n",
          "bech32":"bc",
          "bip32":{
             "public":76067358,
             "private":76066276
          },
          "pubKeyHash":0,
          "scriptHash":5,
          "wif":128
       },
       "coinNumber":61
    },
    "ETH":{
       "shortName":"ETH",
       "longName":"Ethereum",
       "network":{
          "messagePrefix":"\u0018Bitcoin Signed Message:\n",
          "bech32":"bc",
          "bip32":{
             "public":76067358,
             "private":76066276
          },
          "pubKeyHash":0,
          "scriptHash":5,
          "wif":128
       },
       "coinNumber":60
    },
    "EWT":{
       "shortName":"EWT",
       "longName":"EnergyWeb",
       "network":{
          "messagePrefix":"\u0018Bitcoin Signed Message:\n",
          "bech32":"bc",
          "bip32":{
             "public":76067358,
             "private":76066276
          },
          "pubKeyHash":0,
          "scriptHash":5,
          "wif":128
       },
       "coinNumber":246
    },
    "EXCL":{
       "shortName":"EXCL",
       "longName":"Exclusivecoin",
       "network":{
          "messagePrefix":"\u0018ExclusiveCoin Signed Message:\n",
          "bip32":{
             "public":76067358,
             "private":76066276
          },
          "pubKeyHash":33,
          "scriptHash":137,
          "wif":161
       },
       "coinNumber":190
    },
    "EXCC":{
       "shortName":"EXCC",
       "longName":"ExchangeCoin",
       "network":{
          "messagePrefix":"ExchangeCoin Signed Message:\n",
          "bip32":{
             "public":76067358,
             "private":76066276
          },
          "pubKeyHash":8633,
          "scriptHash":13487,
          "wif":128
       },
       "coinNumber":0
    },
    "EXP":{
       "shortName":"EXP",
       "longName":"Expanse",
       "segwitAvailable":false,
       "network":{
          "messagePrefix":"\u0018Bitcoin Signed Message:\n",
          "bech32":"bc",
          "bip32":{
             "public":76067358,
             "private":76066276
          },
          "pubKeyHash":0,
          "scriptHash":5,
          "wif":128
       },
       "coinNumber":40
    },
    "FIO":{
       "shortName":"FIO",
       "longName":"Foundation for Interwallet Operability",
       "network":{
          "messagePrefix":"\u0018Bitcoin Signed Message:\n",
          "bech32":"bc",
          "bip32":{
             "public":76067358,
             "private":76066276
          },
          "pubKeyHash":0,
          "scriptHash":5,
          "wif":128
       },
       "coinNumber":235
    },
    "FIRO":{
       "shortName":"FIRO",
       "longName":"Firo (Zcoin rebrand)",
       "network":{
          "messagePrefix":"\u0018Firo Signed Message:\n",
          "bip32":{
             "public":76067358,
             "private":76066276
          },
          "pubKeyHash":82,
          "scriptHash":7,
          "wif":210
       },
       "coinNumber":136
    },
    "FIX":{
       "shortName":"FIX",
       "longName":"FIX",
       "network":{
            "messagePrefix": 'unused',
            "bip32": {
                "public": 0x022d2533,
                "private": 0x0221312b
            },
            "pubKeyHash": 0x23,
            "scriptHash": 0x5F,
            "wif": 0x3C
        },
       "coinNumber":336
    },
    "FIXt":{
        "shortName":"FIXt",
        "longName":"FIX Testnet",
        "network":{
           "messagePrefix":"unused",
           "bip32":{
              "public":981492128,
              "private":981489719
           },
           "pubKeyHash":76,
           "scriptHash":137,
           "wif":237
        },
        "coinNumber":1
     },
    "FJC":{
       "shortName":"FJC",
       "longName":"Fujicoin",
       "network":{
          "messagePrefix":"\u0019FujiCoin Signed Message:\n",
          "bip32":{
             "public":76067358,
             "private":76066276
          },
          "pubKeyHash":36,
          "scriptHash":16,
          "wif":164,
          "p2wpkh":{
            "baseNetwork":"fujicoin",
            "messagePrefix":"\\x19FujiCoin Signed Message:\n",
            "bech32":"fc",
            "bip32":{
               "public":0x04b24746,
               "private":0x04b2430c
            },
            "pubKeyHash":0x24,
            "scriptHash":0x10,
            "wif":0xa4
         },
         "p2wpkhInP2sh":{
            "baseNetwork":"fujicoin",
            "messagePrefix":"\\x19FujiCoin Signed Message:\n",
            "bech32":"fc",
            "bip32":{
               "public":0x049d7cb2,
               "private":0x049d7878
            },
            "pubKeyHash":0x24,
            "scriptHash":0x10,
            "wif":0xa4
         }
       },
       "coinNumber":75
    },
    "FLASH":{
       "shortName":"FLASH",
       "longName":"Flashcoin",
       "network":{
          "messagePrefix":"\u0018Flashcoin Signed Message:\n",
          "bip32":{
             "public":76067358,
             "private":76066276
          },
          "pubKeyHash":68,
          "scriptHash":130,
          "wif":196
       },
       "coinNumber":120
    },
    "FRST":{
       "shortName":"FRST",
       "longName":"Firstcoin",
       "network":{
          "messagePrefix":"\u0018FirstCoin Signed Message:\n",
          "bip32":{
             "public":76067358,
             "private":76066276
          },
          "pubKeyHash":35,
          "scriptHash":5,
          "wif":163
       },
       "coinNumber":167
    },
    "FTC":{
       "shortName":"FTC",
       "longName":"Feathercoin",
       "network":{
          "messagePrefix":"\u0018Feathercoin Signed Message:\n",
          "bip32":{
             "public":76069926,
             "private":76077806
          },
          "pubKeyHash":14,
          "scriptHash":5,
          "wif":142
       },
       "coinNumber":8
    },
    "GAME":{
       "shortName":"GAME",
       "longName":"GameCredits",
       "network":{
          "messagePrefix":"unused",
          "bip32":{
             "public":76067358,
             "private":76066276
          },
          "pubKeyHash":38,
          "scriptHash":5,
          "wif":166
       },
       "coinNumber":101
    },
    "GBX":{
       "shortName":"GBX",
       "longName":"Gobyte",
       "network":{
          "messagePrefix":"\u0018DarkCoin Signed Message:\n",
          "bip32":{
             "public":76067358,
             "private":76066276
          },
          "pubKeyHash":38,
          "scriptHash":10,
          "wif":198
       },
       "coinNumber":176
    },
    "GCR":{
       "shortName":"GCR",
       "longName":"GCRCoin",
       "network":{
          "messagePrefix":"\u0018GCR Signed Message:\n",
          "bip32":{
             "public":76067358,
             "private":76066276
          },
          "pubKeyHash":38,
          "scriptHash":97,
          "wif":154
       },
       "coinNumber":79
    },
    "GRC":{
       "shortName":"GRC",
       "longName":"Gridcoin",
       "network":{
          "messagePrefix":"\u0018Gridcoin Signed Message:\n",
          "bip32":{
             "public":76067358,
             "private":76066276
          },
          "pubKeyHash":62,
          "scriptHash":85,
          "wif":190
       },
       "coinNumber":84
    },
    "GRS":{
       "shortName":"GRS",
       "longName":"Groestlcoin",
       "network":{
            "messagePrefix": '\x19GroestlCoin Signed Message:\n',
            "bip32": {
                "public": 0x0488b21e,
                "private": 0x0488ade4
            },
            "pubKeyHash": 36,
            "scriptHash": 5,
            "wif": 128,
            "p2wpkh":{
               "baseNetwork":"groestlcoin",
               "messagePrefix":"\\x19GroestlCoin Signed Message:\n",
               "bech32":"grs",
               "bip32":{
                  "public":0x04b24746,
                  "private":0x04b2430c
               },
               "pubKeyHash":0x24,
               "scriptHash":0x05,
               "wif":0x80
            },
            "p2wpkhInP2sh":{
               "baseNetwork":"groestlcoin",
               "messagePrefix":"\\x19GroestlCoin Signed Message:\n",
               "bech32":"grs",
               "bip32":{
                  "public":0x049d7cb2,
                  "private":0x049d7878
               },
               "pubKeyHash":0x24,
               "scriptHash":0x05,
               "wif":0x80
            }
        },
       "coinNumber":17
    },
    "GRSt":{
        "shortName":"GRSt",
        "longName":"Groestlcoin Testnet",
        "network":{
           "messagePrefix":"\u0019GroestlCoin Signed Message:\n",
           "bip32":{
              "public":70617039,
              "private":70615956
           },
           "pubKeyHash":111,
           "scriptHash":196,
           "wif":239,
         "p2wpkh":{
            "baseNetwork":"groestlcointestnet",
            "messagePrefix":"\\x19GroestlCoin Signed Message:\n",
            "bech32":"tgrs",
            "bip32":{
               "public":0x045f1cf6,
               "private":0x045f18bc
            },
            "pubKeyHash":0x6f,
            "scriptHash":0xc4,
            "wif":0xef
         },
         "p2wpkhInP2sh":{
            "baseNetwork":"groestlcointestnet",
            "messagePrefix":"\\x19GroestlCoin Signed Message:\n",
            "bech32":"tgrs",
            "bip32":{
               "public":0x044a5262,
               "private":0x044a4e28
            },
            "pubKeyHash":0x6f,
            "scriptHash":0xc4,
            "wif":0xef
         }
        },
        "coinNumber":1
     },
    "HNS":{
       "shortName":"HNS",
       "longName":"Handshake",
       "coinNumber":5353
    },
    "HNC":{
       "shortName":"HNC",
       "longName":"Helleniccoin",
       "network":{
          "messagePrefix":"\u0018helleniccoin Signed Message:\n",
          "bip32":{
             "public":76067358,
             "private":76066276
          },
          "pubKeyHash":48,
          "scriptHash":5,
          "wif":176
       },
       "coinNumber":168
    },
    "HUSH":{
       "shortName":"HUSH",
       "longName":"Hush3",
       "network":{
          "messagePrefix":"\u0018Hush Signed Message:\n",
          "bip32":{
             "public":76067358,
             "private":76066276
          },
          "pubKeyHash":60,
          "scriptHash":85,
          "wif":188
       },
       "coinNumber":197
    },
    "INSN":{
       "shortName":"INSN",
       "longName":"Insane",
       "network":{
          "messagePrefix":"\u0018INSaNe Signed Message:\n",
          "bip32":{
             "public":76067358,
             "private":76066276
          },
          "pubKeyHash":102,
          "scriptHash":57,
          "wif":55
       },
       "coinNumber":68
    },
    "IOP":{
       "shortName":"IOP",
       "longName":"Iop",
       "network":{
          "messagePrefix":"\u0018IoP Signed Message:\n",
          "bip32":{
             "public":662737247,
             "private":2922649334
          },
          "pubKeyHash":117,
          "scriptHash":174,
          "wif":49
       },
       "coinNumber":66
    },
    "IXC":{
       "shortName":"IXC",
       "longName":"Ixcoin",
       "network":{
          "messagePrefix":"\u0018Ixcoin Signed Message:\n",
          "bip32":{
             "public":76067358,
             "private":76066276
          },
          "pubKeyHash":138,
          "scriptHash":5,
          "wif":128
       },
       "coinNumber":86
    },
    "JBS":{
       "shortName":"JBS",
       "longName":"Jumbucks",
       "network":{
          "messagePrefix":"\u0019Jumbucks Signed Message:\n",
          "bip32":{
             "public":58353818,
             "private":58352736
          },
          "pubKeyHash":43,
          "scriptHash":5,
          "wif":171
       },
       "coinNumber":26
    },
    "KMD":{
       "shortName":"KMD",
       "longName":"Komodo",
       "bip49available":false,
       "network":{
          "messagePrefix":"\u0018Komodo Signed Message:\n",
          "bip32":{
             "public":76067358,
             "private":76066276
          },
          "pubKeyHash":60,
          "scriptHash":85,
          "wif":188
       },
       "coinNumber":141
    },
    "KOBO":{
       "shortName":"KOBO",
       "longName":"Kobocoin",
       "bip49available":false,
       "network":{
          "messagePrefix":"\u0018Kobocoin Signed Message:\n",
          "bip32":{
             "public":76067358,
             "private":76066276
          },
          "pubKeyHash":35,
          "scriptHash":28,
          "wif":163
       },
       "coinNumber":196
    },
    "LBC":{
       "shortName":"LBC",
       "longName":"Library Credits",
       "network":{
          "messagePrefix":"\u0018LBRYcrd Signed Message:\n",
          "bip32":{
             "public":76067358,
             "private":76066276
          },
          "pubKeyHash":85,
          "scriptHash":122,
          "wif":28
       },
       "coinNumber":140
    },
    "LCC":{
       "shortName":"LCC",
       "longName":"Litecoincash",
       "network":{
          "messagePrefix":"\u0018Litecoin Signed Message:\n",
          "bip32":{
             "public":76067358,
             "private":76066276
          },
          "pubKeyHash":28,
          "scriptHash":5,
          "wif":176
       },
       "coinNumber":192
    },
    "LDCN":{
       "shortName":"LDCN",
       "longName":"Landcoin",
       "network":{
          "messagePrefix":"\u0018Landcoin Signed Message:\n",
          "bip32":{
             "public":76067358,
             "private":76066276
          },
          "pubKeyHash":48,
          "scriptHash":122,
          "wif":176
       },
       "coinNumber":63
    },
    "LINX":{
       "shortName":"LINX",
       "longName":"Linx",
       "network":{
          "messagePrefix":"\u0018LinX Signed Message:\n",
          "bip32":{
             "public":76067358,
             "private":76066276
          },
          "pubKeyHash":75,
          "scriptHash":5,
          "wif":203
       },
       "coinNumber":114
    },
    "LKR":{
       "shortName":"LKR",
       "longName":"Lkrcoin",
       "segwitAvailable":false,
       "network":{
          "messagePrefix":"\u0018LKRcoin Signed Message:\n",
          "bip32":{
             "public":76067358,
             "private":76066276
          },
          "pubKeyHash":48,
          "scriptHash":85,
          "wif":176
       },
       "coinNumber":557
    },
    "LTC":{
       "shortName":"LTC",
       "longName":"Litecoin",
       "network":{
         "p2wpkh":{
            "baseNetwork":"litecoin",
            "messagePrefix":"\\x19Litecoin Signed Message:\n",
            "bech32":"ltc",
            "bip32":{
               "public":0x04b24746,
               "private":0x04b2430c
            },
            "pubKeyHash":0x30,
            "scriptHash":0x32,
            "wif":0xb0
         },
         "p2wpkhInP2sh":{
            "baseNetwork":"litecoin",
            "messagePrefix":"\\x19Litecoin Signed Message:\n",
            "bech32":"ltc",
            "bip32":{
               "public":0x01b26ef6,
               "private":0x01b26792
            },
            "pubKeyHash":0x30,
            "scriptHash":0x32,
            "wif":0xb0
         }
       },
       "coinNumber":2
    },
    "LTCt":{
       "shortName":"LTCt",
       "longName":"Litecoin Testnet",
       "network":{
          "messagePrefix":"\u0018Litecoin Signed Message:\n",
          "bip32":{
             "public":70617039,
             "private":70615956
          },
          "pubKeyHash":111,
          "scriptHash":196,
          "wif":239,
          "p2wpkh":{
            "baseNetwork":"litecointestnet",
            "messagePrefix":"\\x18Litecoin Signed Message:\n",
            "bech32":"litecointestnet",
            "bip32":{
               "public":0x043587cf,
               "private":0x04358394
            },
            "pubKeyHash":0x6f,
            "scriptHash":0xc4,
            "wif":0xef
         },
         "p2wpkhInP2sh":{
            "baseNetwork":"litecointestnet",
            "messagePrefix":"\\x18Litecoin Signed Message:\n",
            "bech32":"litecointestnet",
            "bip32":{
               "public":0x043587cf,
               "private":0x04358394
            },
            "pubKeyHash":0x6f,
            "scriptHash":0xc4,
            "wif":0xef
         }
       },
       "coinNumber":1
    },
    "LTZ":{
       "shortName":"LTZ",
       "longName":"LitecoinZ",
       "network":{
          "messagePrefix":"\u0018LitecoinZ Signed Message:\n",
          "bip32":{
             "public":76067358,
             "private":76066275
          },
          "pubKeyHash":2739,
          "scriptHash":2744,
          "wif":128
       },
       "coinNumber":221
    },
    "LYNX":{
       "shortName":"LYNX",
       "longName":"Lynx",
       "network":{
          "messagePrefix":"\u0018Lynx Signed Message:\n",
          "bip32":{
             "public":76067358,
             "private":76066276
          },
          "pubKeyHash":45,
          "scriptHash":50,
          "wif":173
       },
       "coinNumber":191
    },
    "MAZA":{
       "shortName":"MAZA",
       "longName":"Maza",
       "network":{
          "messagePrefix":"unused",
          "bip32":{
             "public":76067358,
             "private":76066276
          },
          "pubKeyHash":50,
          "scriptHash":9,
          "wif":224
       },
       "coinNumber":13
    },
    "MEC":{
       "shortName":"MEC",
       "longName":"Megacoin",
       "network":{
          "messagePrefix":"\u0018Megacoin Signed Message:\n",
          "bip32":{
             "public":76067358,
             "private":76066276
          },
          "pubKeyHash":50,
          "scriptHash":5,
          "wif":178
       },
       "coinNumber":217
    },
    "MIX":{
       "shortName":"MIX",
       "longName":"MIX",
       "segwitAvailable":false,
       "network":{
          "messagePrefix":"\u0018Bitcoin Signed Message:\n",
          "bech32":"bc",
          "bip32":{
             "public":76067358,
             "private":76066276
          },
          "pubKeyHash":0,
          "scriptHash":5,
          "wif":128
       },
       "coinNumber":76
    },
    "MNX":{
       "shortName":"MNX",
       "longName":"Minexcoin",
       "network":{
          "messagePrefix":"\u0018Bitcoin Signed Message:\n",
          "bip32":{
             "public":76067358,
             "private":76066276
          },
          "pubKeyHash":75,
          "scriptHash":5,
          "wif":128
       },
       "coinNumber":182
    },
    "MONA":{
       "shortName":"MONA",
       "longName":"Monacoin",
       "network":{
          "messagePrefix":"\u0018Monacoin Signed Message:\n",
          "bip32":{
             "public":76067358,
             "private":76066276
          },
          "pubKeyHash":50,
          "scriptHash":55,
          "wif":176,
          "p2wpkh":{
            "baseNetwork":"monacoin",
            "messagePrefix":"\\x18Monacoin Signed Message:\n",
            "bech32":"mona",
            "bip32":{
               "public":0x0488b21e,
               "private":0x0488ade4
            },
            "pubKeyHash":0x32,
            "scriptHash":0x37,
            "wif":0xb0
         },
         "p2wpkhInP2sh":{
            "baseNetwork":"monacoin",
            "messagePrefix":"\\x18Monacoin Signed Message:\n",
            "bech32":"mona",
            "bip32":{
               "public":0x0488b21e,
               "private":0x0488ade4
            },
            "pubKeyHash":0x32,
            "scriptHash":0x37,
            "wif":0xb0
         }
       },
       "coinNumber":22
    },
    "MONK":{
       "shortName":"MONK",
       "longName":"Monkey Project",
       "network":{
          "messagePrefix":"Monkey Signed Message:\n",
          "bip32":{
             "public":76067358,
             "private":76078564
          },
          "pubKeyHash":51,
          "scriptHash":28,
          "wif":55,
          "p2wpkh":{
            "baseNetwork":"monkeyproject",
            "messagePrefix":"Monkey Signed Message:\n",
            "bech32":"monkey",
            "bip32":{
               "public":0x0488b21e,
               "private":0x0488dde4
            },
            "pubKeyHash":0x33,
            "scriptHash":0x1c,
            "wif":0x37,
         },
         "p2wpkhInP2sh":{
            "baseNetwork":"monkeyproject",
            "messagePrefix":"Monkey Signed Message:\n",
            "bech32":"monkey",
            "bip32":{
               "public":0x0488b21e,
               "private":0x0488dde4
            },
            "pubKeyHash":0x33,
            "scriptHash":0x1c,
            "wif":0x37
         }
       },
       "coinNumber":214
    },
    "MOAC":{
       "shortName":"MOAC",
       "longName":"MOAC",
       "segwitAvailable":false,
       "network":{
          "messagePrefix":"\u0018Bitcoin Signed Message:\n",
          "bech32":"bc",
          "bip32":{
             "public":76067358,
             "private":76066276
          },
          "pubKeyHash":0,
          "scriptHash":5,
          "wif":128
       },
       "coinNumber":314
    },
    "MUSIC":{
       "shortName":"MUSIC",
       "longName":"Musicoin",
       "segwitAvailable":false,
       "network":{
          "messagePrefix":"\u0018Bitcoin Signed Message:\n",
          "bech32":"bc",
          "bip32":{
             "public":76067358,
             "private":76066276
          },
          "pubKeyHash":0,
          "scriptHash":5,
          "wif":128
       },
       "coinNumber":184
    },
    "NANO":{
       "shortName":"NANO",
       "longName":"Nano",
       "network":"dummyNetwork",
       "coinNumber":165
    },
    "NAV":{
       "shortName":"NAV",
       "longName":"Navcoin",
       "network":{
          "messagePrefix":"\u0018Navcoin Signed Message:\n",
          "bip32":{
             "public":76067358,
             "private":76066276
          },
          "pubKeyHash":53,
          "scriptHash":85,
          "wif":150
       },
       "coinNumber":130
    },
    "NAS":{
       "shortName":"NAS",
       "longName":"Nebulas",
       "network":{
          "messagePrefix":"\u0018Bitcoin Signed Message:\n",
          "bech32":"bc",
          "bip32":{
             "public":76067358,
             "private":76066276
          },
          "pubKeyHash":0,
          "scriptHash":5,
          "wif":128
       },
       "coinNumber":2718
    },
    "NEBL":{
       "shortName":"NEBL",
       "longName":"Neblio",
       "network":{
          "messagePrefix":"\u0018Neblio Signed Message:\n",
          "bip32":{
             "public":76067358,
             "private":76066276
          },
          "pubKeyHash":53,
          "scriptHash":112,
          "wif":181
       },
       "coinNumber":146
    },
    "NEOS":{
       "shortName":"NEOS",
       "longName":"Neoscoin",
       "network":{
          "messagePrefix":"\u0018NeosCoin Signed Message:\n",
          "bip32":{
             "public":76067358,
             "private":76066276
          },
          "pubKeyHash":53,
          "scriptHash":5,
          "wif":177
       },
       "coinNumber":25
    },
    "NIX":{
       "shortName":"NIX",
       "longName":"NIX Platform",
       "network":{
          "messagePrefix":"\u0018Nix Signed Message:\n",
          "bip32":{
             "public":76067358,
             "private":76066276
          },
          "pubKeyHash":38,
          "scriptHash":53,
          "wif":128,
          "p2wpkh":{
            "baseNetwork":"nix",
            "messagePrefix":"\\x18Nix Signed Message:\n",
            "bech32":"nix",
            "bip32":{
               "public":0x0488b21e,
               "private":0x0488ade4
            },
            "pubKeyHash":0x26,
            "scriptHash":0x35,
            "wif":0x80
         },
         "p2wpkhInP2sh":{
            "baseNetwork":"nix",
            "messagePrefix":"\\x18Nix Signed Message:\n",
            "bech32":"nix",
            "bip32":{
               "public":0x0488b21e,
               "private":0x0488ade4
            },
            "pubKeyHash":0x26,
            "scriptHash":0x35,
            "wif":0x80
         }
       },
       "coinNumber":400
    },
    "NLG":{
       "shortName":"NLG",
       "longName":"Gulden",
       "network":{
          "messagePrefix":"\u0018Guldencoin Signed Message:\n",
          "bip32":{
             "public":76067358,
             "private":76066276
          },
          "pubKeyHash":38,
          "scriptHash":98,
          "wif":98
       },
       "coinNumber":87
    },
    "NMC":{
       "shortName":"NMC",
       "longName":"Namecoin",
       "network":{
          "messagePrefix":"unused",
          "bip32":{
             "public":76067358,
             "private":76066276
          },
          "pubKeyHash":52,
          "scriptHash":13,
          "wif":128
       },
       "coinNumber":7
    },
    "NRG":{
       "shortName":"NRG",
       "longName":"Energi",
       "network":{
          "messagePrefix":"DarkCoin Signed Message:\n",
          "bip32":{
             "public":62441558,
             "private":3621547679
          },
          "pubKeyHash":33,
          "scriptHash":53,
          "wif":106
       },
       "coinNumber":204
    },
    "NRO":{
       "shortName":"NRO",
       "longName":"Neurocoin",
       "network":{
          "messagePrefix":"\u0018PPCoin Signed Message:\n",
          "bip32":{
             "public":76067358,
             "private":76066276
          },
          "pubKeyHash":53,
          "scriptHash":117,
          "wif":181
       },
       "coinNumber":110
    },
    "NSR":{
       "shortName":"NSR",
       "longName":"Nushares",
       "network":{
          "messagePrefix":"\u0018Nu Signed Message:\n",
          "bip32":{
             "public":76067358,
             "private":76066276
          },
          "pubKeyHash":63,
          "scriptHash":64,
          "wif":149
       },
       "coinNumber":11
    },
    "NYC":{
       "shortName":"NYC",
       "longName":"Newyorkc",
       "network":{
          "messagePrefix":"\u0018newyorkc Signed Message:\n",
          "bip32":{
             "public":76067358,
             "private":76066276
          },
          "pubKeyHash":60,
          "scriptHash":22,
          "wif":188
       },
       "coinNumber":179
    },
    "NVC":{
       "shortName":"NVC",
       "longName":"Novacoin",
       "network":{
          "messagePrefix":"\u0018NovaCoin Signed Message:\n",
          "bip32":{
             "public":76067358,
             "private":76066276
          },
          "pubKeyHash":8,
          "scriptHash":20,
          "wif":136
       },
       "coinNumber":50
    },
    "OK":{
       "shortName":"OK",
       "longName":"Okcash",
       "network":{
          "messagePrefix":"\u0018OKCash Signed Message:\n",
          "bip32":{
             "public":63710167,
             "private":63708275
          },
          "pubKeyHash":55,
          "scriptHash":28,
          "wif":3
       },
       "coinNumber":69
    },
    "OMNI":{
       "shortName":"OMNI",
       "longName":"Omnicore",
       "network":{
          "messagePrefix":"\u0018Bitcoin Signed Message:\n",
          "bip32":{
             "public":76067358,
             "private":76066276
          },
          "pubKeyHash":0,
          "scriptHash":5,
          "wif":128
       },
       "coinNumber":200
    },
    "ONION":{
       "shortName":"ONION",
       "longName":"DeepOnion",
       "network":{
          "messagePrefix":"x18DeepOnion Signed Message:\n",
          "bip32":{
             "public":76067358,
             "private":76066276
          },
          "pubKeyHash":31,
          "scriptHash":78,
          "wif":159,
          "p2wpkh":{
            "baseNetwork":"deeponion",
            "messagePrefix":"\\x18DeepOnion Signed Message:\n",
            "bech32":"dpn",
            "bip32":{
               "public":0x0488b21e,
               "private":0x0488ade4
            },
            "pubKeyHash":0x1f,
            "scriptHash":0x4e,
            "wif":0x9f
         },
         "p2wpkhInP2sh":{
            "baseNetwork":"deeponion",
            "messagePrefix":"\\x18DeepOnion Signed Message:\n",
            "bech32":"dpn",
            "bip32":{
               "public":0x0488b21e,
               "private":0x0488ade4
            },
            "pubKeyHash":0x1f,
            "scriptHash":0x4e,
            "wif":0x9f
         }
       },
       "coinNumber":305
    },
    "ONX":{
       "shortName":"ONX",
       "longName":"Onixcoin",
       "network":{
          "messagePrefix":"ONIX Signed Message:\n",
          "bip32":{
             "public":76067358,
             "private":76066276
          },
          "pubKeyHash":75,
          "scriptHash":5,
          "wif":203
       },
       "coinNumber":174
    },
    "PHR":{
       "shortName":"PHR",
       "longName":"Phore",
       "network":{
          "messagePrefix":"\u0018Phore Signed Message:\n",
          "bip32":{
             "public":36513075,
             "private":35729707
          },
          "pubKeyHash":55,
          "scriptHash":13,
          "wif":212
       },
       "coinNumber":444
    },
    "PINK":{
       "shortName":"PINK",
       "longName":"Pinkcoin",
       "network":{
          "messagePrefix":"\u0018Pinkcoin Signed Message:\n",
          "bip32":{
             "public":76067358,
             "private":76066276
          },
          "pubKeyHash":3,
          "scriptHash":28,
          "wif":131
       },
       "coinNumber":117
    },
    "PIRL":{
       "shortName":"PIRL",
       "longName":"Pirl",
       "segwitAvailable":false,
       "network":{
          "messagePrefix":"\u0018Bitcoin Signed Message:\n",
          "bech32":"bc",
          "bip32":{
             "public":76067358,
             "private":76066276
          },
          "pubKeyHash":0,
          "scriptHash":5,
          "wif":128
       },
       "coinNumber":164
    },
    "PIVX":{
        "shortName":"PIVX",
        "longName":"PIVX",
        "network":{
            "messagePrefix": 'unused',
            "bip32": {
              "public": 0x022d2533,
              "private": 0x0221312b
            },
            "pubKeyHash": 0x1e,
            "scriptHash": 0x0d,
            "wif": 0xd4
        },
        "coinNumber":119
     },
    "PIVXt":{
       "shortName":"PIVX",
       "longName":"PIVX Testnet",
       "network":{
          "messagePrefix":"unused",
          "bip32":{
             "public":981492128,
             "private":981489719
          },
          "pubKeyHash":139,
          "scriptHash":19,
          "wif":239
       },
       "coinNumber":1
    },
    "POA":{
       "shortName":"POA",
       "longName":"Poa",
       "segwitAvailable":false,
       "network":{
          "messagePrefix":"\u0018Bitcoin Signed Message:\n",
          "bech32":"bc",
          "bip32":{
             "public":76067358,
             "private":76066276
          },
          "pubKeyHash":0,
          "scriptHash":5,
          "wif":128
       },
       "coinNumber":178
    },
    "POSW":{
       "shortName":"POSW",
       "longName":"POSWcoin",
       "network":{
          "messagePrefix":"\u0018Poswcoin Signed Message:\n",
          "bip32":{
             "public":76067358,
             "private":76066276
          },
          "pubKeyHash":55,
          "scriptHash":85,
          "wif":183
       },
       "coinNumber":47
    },
    "POT":{
       "shortName":"POT",
       "longName":"Potcoin",
       "network":{
          "messagePrefix":"\u0018Potcoin Signed Message:\n",
          "bip32":{
             "public":76067358,
             "private":76066276
          },
          "pubKeyHash":55,
          "scriptHash":5,
          "wif":183
       },
       "coinNumber":81
    },
    "PPC":{
       "shortName":"PPC",
       "longName":"Peercoin",
       "network":{
          "messagePrefix":"unused",
          "bip32":{
             "public":76067358,
             "private":76066276
          },
          "pubKeyHash":55,
          "scriptHash":117,
          "wif":183
       },
       "coinNumber":6
    },
    "PRJ":{
       "shortName":"PRJ",
       "longName":"ProjectCoin",
       "network":{
          "messagePrefix":"\u0018ProjectCoin Signed Message:\n",
          "bip32":{
             "public":36513075,
             "private":35729707
          },
          "pubKeyHash":55,
          "scriptHash":8,
          "wif":117
       },
       "coinNumber":533
    },
    "PSB":{
       "shortName":"PSB",
       "longName":"Pesobit",
       "network":{
          "messagePrefix":"\u0018Pesobit Signed Message:\n",
          "bip32":{
             "public":76067358,
             "private":76066276
          },
          "pubKeyHash":55,
          "scriptHash":85,
          "wif":183
       },
       "coinNumber":62
    },
    "PUT":{
       "shortName":"PUT",
       "longName":"Putincoin",
       "network":{
          "messagePrefix":"\u0018PutinCoin Signed Message:\n",
          "bip32":{
             "public":76067358,
             "private":76066276
          },
          "pubKeyHash":55,
          "scriptHash":20,
          "wif":183
       },
       "coinNumber":122
    },
    "RPD":{
       "shortName":"RPD",
       "longName":"Rapids",
       "network":{
          "messagePrefix":"DarkNet Signed Message:\n",
          "bip32":{
             "public":76067358,
             "private":76066276
          },
          "pubKeyHash":61,
          "scriptHash":6,
          "wif":46
       },
       "coinNumber":320
    },
    "RVN":{
       "shortName":"RVN",
       "longName":"Ravencoin",
       "network":{
          "messagePrefix":"\u0016Raven Signed Message:\n",
          "bip32":{
             "public":76067358,
             "private":76066276
          },
          "pubKeyHash":60,
          "scriptHash":122,
          "wif":128
       },
       "coinNumber":175
    },
    "R-BTC":{
       "shortName":"R-BTC",
       "longName":"RSK",
       "network":{
          "messagePrefix":"\u0018RSK Signed Message:\n",
          "bip32":{
             "public":76067358,
             "private":76066276
          },
          "pubKeyHash":0,
          "scriptHash":5,
          "wif":128
       },
       "coinNumber":137
    },
    "tR-BTC":{
       "shortName":"tR-BTC",
       "longName":"RSK Testnet",
       "network":{
          "messagePrefix":"\u0018RSK Testnet Signed Message:\n",
          "bip32":{
             "public":70617039,
             "private":70615956
          },
          "pubKeyHash":111,
          "scriptHash":196,
          "wif":239
       },
       "coinNumber":37310
    },
    "RBY":{
       "shortName":"RBY",
       "longName":"Rubycoin",
       "network":{
          "messagePrefix":"\u0018Rubycoin Signed Message:\n",
          "bip32":{
             "public":76067358,
             "private":76066276
          },
          "pubKeyHash":60,
          "scriptHash":85,
          "wif":188
       },
       "coinNumber":16
    },
    "RDD":{
       "shortName":"RDD",
       "longName":"Reddcoin",
       "network":{
          "messagePrefix":"\u0018Reddcoin Signed Message:\n",
          "bip32":{
             "public":76067358,
             "private":76066276
          },
          "pubKeyHash":61,
          "scriptHash":5,
          "wif":189
       },
       "coinNumber":4
    },
    "RVR":{
       "shortName":"RVR",
       "longName":"RevolutionVR",
       "network":{
          "messagePrefix":"\u0018Voxels Signed Message:\n",
          "bip32":{
             "public":76067358,
             "private":76066276
          },
          "pubKeyHash":70,
          "scriptHash":5,
          "wif":198
       },
       "coinNumber":129
    },
    "SAFE":{
       "shortName":"SAFE",
       "longName":"Safecoin",
       "network":{
          "messagePrefix":"\u0018Safecoin Signed Message:\n",
          "bip32":{
             "public":76067358,
             "private":76066276
          },
          "pubKeyHash":61,
          "scriptHash":86,
          "wif":189
       },
       "coinNumber":19165
    },
    "SCRIBE":{
       "shortName":"SCRIBE",
       "longName":"Scribe",
       "network":{
          "messagePrefix":"unused",
          "bip32":{
             "public":76067358,
             "private":76066276
          },
          "pubKeyHash":60,
          "scriptHash":125,
          "wif":110
       },
       "coinNumber":545
    },
    "SLS":{
       "shortName":"SLS",
       "longName":"Salus",
       "network":{
          "messagePrefix":"\u0018Salus Signed Message:\n",
          "bip32":{
             "public":76067358,
             "private":76066276
          },
          "pubKeyHash":63,
          "scriptHash":196,
          "wif":191
       },
       "coinNumber":63
    },
    "SDC":{
        "shortName":"SDC",
        "longName":"ShadowCash",
        "network":{
            "messagePrefix": 'unused',
            "bip32": {
                "public": 0xEE80286A,
                "private": 0xEE8031E8
            },
            "pubKeyHash": 0x3f,
            "scriptHash": 0x7d,
            "wif": 0xbf
        },
        "coinNumber":35
     },
    "SDCt":{
       "shortName":"SDC",
       "longName":"ShadowCash Testnet",
       "network":{
          "messagePrefix":"unused",
          "bip32":{
             "public":1992359419,
             "private":1992361850
          },
          "pubKeyHash":127,
          "scriptHash":196,
          "wif":255
       },
       "coinNumber":1
    },
    "SLM":{
       "shortName":"SLM",
       "longName":"Slimcoin",
       "network":{
        "messagePrefix": 'unused',
            "bip32": {
                "public": 0xef6adf10,
                "private": 0xef69ea80
            },
            "pubKeyHash": 0x3f,
            "scriptHash": 0x7d,
            "wif": 0x46
        },
       "coinNumber":63
    },
    "SLMt":{
        "shortName":"SLM",
        "longName":"Slimcoin Testnet",
        "network":{
           "messagePrefix":"unused",
           "bip32":{
              "public":70617039,
              "private":70615956
           },
           "pubKeyHash":111,
           "scriptHash":196,
           "wif":87
        },
        "coinNumber":111
     },
    "SLP":{
       "shortName":"SLP",
       "longName":"Simple Ledger Protocol",
       "network":"dummyNetwork",
       "coinNumber":245
    },
    "SLR":{
       "shortName":"SLR",
       "longName":"Solarcoin",
       "network":{
          "messagePrefix":"\u0018SolarCoin Signed Message:\n",
          "bip32":{
             "public":76067358,
             "private":76066276
          },
          "pubKeyHash":18,
          "scriptHash":5,
          "wif":146
       },
       "coinNumber":58
    },
    "SMLY":{
       "shortName":"SMLY",
       "longName":"Smileycoin",
       "network":{
          "messagePrefix":"\u0018Smileycoin Signed Message:\n",
          "bip32":{
             "public":508964250,
             "private":508965308
          },
          "pubKeyHash":25,
          "scriptHash":5,
          "wif":5
       },
       "coinNumber":59
    },
    "STASH":{
        "shortName":"STASH",
        "longName":"Stash",
        "network":{
            "messagePrefix": '\x18Stash Signed Message:\n',
            "bip32": {
              "public": 0x0488b21e,
              "private": 0x0488ade4
            },
            "pubKeyHash": 0x4c,
            "scriptHash": 0x10,
            "wif": 0xcc
        },
        "coinNumber":0xC0C0
     },
    "STASHt":{
       "shortName":"STASHt",
       "longName":"Stash Testnet",
       "network":{
          "messagePrefix":"\u0018Stash Test Signed Message:\n",
          "bip32":{
             "public":70617039,
             "private":70615956
          },
          "pubKeyHash":140,
          "scriptHash":19,
          "wif":239
       },
       "coinNumber":0xCAFE
    },
    "STRAT":{
       "shortName":"STRAT",
       "longName":"Stratis",
       "network":{
          "messagePrefix":"\u0018Stratis Signed Message:\n",
          "bip32":{
             "public":76067358,
             "private":76066276
          },
          "pubKeyHash":63,
          "scriptHash":125,
          "wif":191
       },
       "coinNumber":105
    },
    "SUGAR":{
       "shortName":"SUGAR",
       "longName":"Sugarchain",
       "network":{
          "messagePrefix":"\u0018Sugarchain Signed Message:\n",
          "bip32":{
             "public":76067358,
             "private":76066276
          },
          "pubKeyHash":63,
          "scriptHash":125,
          "wif":128,
          "p2wpkh":{
            "baseNetwork":"sugarchain",
            "messagePrefix":"\\x1DSugarchain Signed Message:\n",
            "bech32":"sugar",
            "bip32":{
               "public":0x04b24746,
               "private":0x04b2430c
            },
            "pubKeyHash":0x3f,
            "scriptHash":0x7d,
            "wif":0x80
         },
         "p2wpkhInP2sh":{
            "baseNetwork":"sugarchain",
            "messagePrefix":"\\x1DSugarchain Signed Message:\n",
            "bech32":"sugar",
            "bip32":{
               "public":0x049d7cb2,
               "private":0x049d7878
            },
            "pubKeyHash":0x3f,
            "scriptHash":0x7d,
            "wif":0x80
         }
       },
       "coinNumber":408
    },
    "TUGAR":{
       "shortName":"TUGAR",
       "longName":"Sugarchain Testnet",
       "network":{
          "messagePrefix":"\u0018Sugarchain Signed Message:\n",
          "bip32":{
             "public":73342198,
             "private":73341116
          },
          "pubKeyHash":66,
          "scriptHash":128,
          "wif":239,
          "p2wpkh":{
            "baseNetwork":"sugarchaintestnet",
            "messagePrefix":"\\x18Sugarchain Signed Message:\n",
            "bech32":"tugar",
            "bip32":{
               "public":0x045f1cf6,
               "private":0x045f18bc
            },
            "pubKeyHash":0x42,
            "scriptHash":0x80,
            "wif":0xef,
         },
         "p2wpkhInP2sh":{
            "baseNetwork":"sugarchaintestnet",
            "messagePrefix":"\\x18Sugarchain Signed Message:\n",
            "bech32":"tugar",
            "bip32":{
               "public":0x044a5262,
               "private":0x044a4e28
            },
            "pubKeyHash":0x42,
            "scriptHash":0x80,
            "wif":0xef
         }
       },
       "coinNumber":408
    },
    "SWTC":{
       "shortName":"SWTC",
       "longName":"Jingtum",
       "network":{
          "messagePrefix":"\u0018Bitcoin Signed Message:\n",
          "bech32":"bc",
          "bip32":{
             "public":76067358,
             "private":76066276
          },
          "pubKeyHash":0,
          "scriptHash":5,
          "wif":128
       },
       "coinNumber":315
    },
    "TSTRAT":{
       "shortName":"TSTRAT",
       "longName":"Stratis Testnet",
       "network":{
          "messagePrefix":"\u0018Stratis Test Signed Message:\n",
          "bip32":{
             "public":76067358,
             "private":76066276
          },
          "pubKeyHash":65,
          "scriptHash":125,
          "wif":191
       },
       "coinNumber":105
    },
    "SYS":{
       "shortName":"SYS",
       "longName":"Syscoin",
       "network":{
          "messagePrefix":"\u0018Syscoin Signed Message:\n",
          "bip32":{
             "public":76067358,
             "private":76066276
          },
          "pubKeyHash":63,
          "scriptHash":5,
          "wif":128,
          "p2wpkh":{
            "baseNetwork":"syscoin",
            "messagePrefix":"\\x18Syscoin Signed Message:\n",
            "bech32":"sys",
            "bip32":{
               "public":0x04b24746,
               "private":0x04b2430c
            },
            "pubKeyHash":0x3f,
            "scriptHash":0x05,
            "wif":0x80
         },
         "p2wpkhInP2sh":{
            "baseNetwork":"syscoin",
            "messagePrefix":"\\x18Syscoin Signed Message:\n",
            "bech32":"sys",
            "bip32":{
               "public":0x049d7cb2,
               "private":0x049d7878
            },
            "pubKeyHash":0x3f,
            "scriptHash":0x05,
            "wif":0x80
         }
       },
       "coinNumber":57
    },
    "THC":{
       "shortName":"THC",
       "longName":"Hempcoin",
       "network":{
          "messagePrefix":"\u0018Hempcoin Signed Message:\n",
          "bip32":{
             "public":76067358,
             "private":76066276
          },
          "pubKeyHash":40,
          "scriptHash":8,
          "wif":168
       },
       "coinNumber":113
    },
    "THT":{
       "shortName":"THT",
       "longName":"Thought",
       "network":{
          "messagePrefix":"unused",
          "bip32":{
             "public":4224098317,
             "private":1525405894
          },
          "pubKeyHash":7,
          "scriptHash":9,
          "wif":123
       },
       "coinNumber":1618
    },
    "TOA":{
       "shortName":"TOA",
       "longName":"Toa",
       "network":{
          "messagePrefix":"\u0018TOA Signed Message:\n",
          "bip32":{
             "public":76067358,
             "private":76066276
          },
          "pubKeyHash":65,
          "scriptHash":23,
          "wif":193
       },
       "coinNumber":159
    },
    "TRX":{
       "shortName":"TRX",
       "longName":"Tron",
       "network":"dummyNetwork",
       "coinNumver":195
    },
    "TWINS":{
        "shortName":"TWINS",
        "longName":"TWINS",
        "network":{
            "messagePrefix": 'unused',
            "bip32": {
              "public": 0x022d2533,
              "private": 0x0221312b
            },
            "pubKeyHash": 0x49,
            "scriptHash": 0x53,
            "wif": 0x42
        },
        "coinNumber":970
     },
    "TWINSt":{
       "shortName":"TWINSt",
       "longName":"TWINS Testnet",
       "network":{
          "messagePrefix":"unused",
          "bip32":{
             "public":981492128,
             "private":981489719
          },
          "pubKeyHash":76,
          "scriptHash":137,
          "wif":237
       },
       "coinNumber":1
    },
    "USC":{
       "shortName":"USC",
       "longName":"Ultimatesecurecash",
       "network":{
          "messagePrefix":"\u0018UltimateSecureCash Signed Message:\n",
          "bip32":{
             "public":4001376362,
             "private":4001378792
          },
          "pubKeyHash":68,
          "scriptHash":125,
          "wif":191
       },
       "coinNumber":112
    },
    "USNBT":{
       "shortName":"USNBT",
       "longName":"NuBits",
       "network":{
          "messagePrefix":"\u0018Nu Signed Message:\n",
          "bip32":{
             "public":76067358,
             "private":76066276
          },
          "pubKeyHash":25,
          "scriptHash":26,
          "wif":150
       },
       "coinNumber":12
    },
    "UNO":{
       "shortName":"UNO",
       "longName":"Unobtanium",
       "network":{
          "messagePrefix":"\u0018Unobtanium Signed Message:\n",
          "bip32":{
             "public":76067358,
             "private":76066276
          },
          "pubKeyHash":130,
          "scriptHash":30,
          "wif":224
       },
       "coinNumber":92
    },
    "VASH":{
       "shortName":"VASH",
       "longName":"Vpncoin",
       "network":{
          "messagePrefix":"\u0018VpnCoin Signed Message:\n",
          "bip32":{
             "public":76067358,
             "private":76066276
          },
          "pubKeyHash":71,
          "scriptHash":5,
          "wif":199
       },
       "coinNumber":33
    },
    "VET":{
       "shortName":"VET",
       "longName":"VeChain",
       "network":{
          "messagePrefix":"\u0018Bitcoin Signed Message:\n",
          "bech32":"bc",
          "bip32":{
             "public":76067358,
             "private":76066276
          },
          "pubKeyHash":0,
          "scriptHash":5,
          "wif":128
       },
       "coinNumber":818
    },
    "VIA":{
        "shortName":"VIA",
        "longName":"Viacoin",
        "network":{
            "messagePrefix": '\x18Viacoin Signed Message:\n',
            "bip32": {
              "public": 0x0488b21e,
              "private": 0x0488ade4
            },
            "pubKeyHash": 0x47,
            "scriptHash": 0x21,
            "wif": 0xc7,
            "p2wpkh":{
               "baseNetwork":"viacoin",
               "messagePrefix":"\\x18Viacoin Signed Message:\n",
               "bech32":"viacoin",
               "bip32":{
                  "public":0x0488b21e,
                  "private":0x0488ade4
               },
               "pubKeyHash":0x47,
               "scriptHash":0x21,
               "wif":0xc7
            },
            "p2wpkhInP2sh":{
               "baseNetwork":"viacoin",
               "messagePrefix":"\\x18Viacoin Signed Message:\n",
               "bech32":"viacoin",
               "bip32":{
                  "public":0x0488b21e,
                  "private":0x0488ade4
               },
               "pubKeyHash":0x47,
               "scriptHash":0x21,
               "wif":0xc7
            }
        },
        "coinNumber":14
     },
    "VIAt":{
       "shortName":"VIAt",
       "longName":"Viacoin Testnet",
       "network":{
          "messagePrefix":"\u0018Viacoin Signed Message:\n",
          "bip32":{
             "public":70617039,
             "private":70615956
          },
          "pubKeyHash":127,
          "scriptHash":196,
          "wif":255
       },
       "coinNumber":1
    },
    "VIVO":{
       "shortName":"VIVO",
       "longName":"Vivo",
       "network":{
          "messagePrefix":"\u0018DarkCoin Signed Message:\n",
          "bip32":{
             "public":76067358,
             "private":76066276
          },
          "pubKeyHash":70,
          "scriptHash":10,
          "wif":198
       },
       "coinNumber":166
    },
    "VTC":{
       "shortName":"VTC",
       "longName":"Vertcoin",
       "network":{
          "messagePrefix":"\u0018Vertcoin Signed Message:\n",
          "bip32":{
             "public":76067358,
             "private":76066276
          },
          "pubKeyHash":71,
          "scriptHash":5,
          "wif":128,
          "p2wpkh":{
            "baseNetwork":"vertcoin",
            "messagePrefix":"\\x18Vertcoin Signed Message:\n",
            "bech32":"vtc",
            "bip32":{
               "public":0x0488b21e,
               "private":0x0488ade4
            },
            "pubKeyHash":71,
            "scriptHash":5,
            "wif":0x80
         },
         "p2wpkhInP2sh":{
            "baseNetwork":"vertcoin",
            "messagePrefix":"\\x18Vertcoin Signed Message:\n",
            "bip32":{
               "public":0x0488b21e,
               "private":0x0488ade4
            },
            "pubKeyHash":71,
            "scriptHash":5,
            "wif":0x80
         }
       },
       "coinNumber":28
    },
    "WGR":{
       "shortName":"WGR",
       "longName":"Wagerr",
       "network":{
          "messagePrefix":"unused",
          "bip32":{
             "public":36513075,
             "private":35729707
          },
          "pubKeyHash":73,
          "scriptHash":63,
          "wif":199
       },
       "coinNumber":7825266
    },
    "WC":{
       "shortName":"WC",
       "longName":"Wincoin",
       "network":{
          "messagePrefix":"\u0018WinCoin Signed Message:\n",
          "bip32":{
             "public":76067358,
             "private":76066276
          },
          "pubKeyHash":73,
          "scriptHash":28,
          "wif":201
       },
       "coinNumber":181
    },
    "XAX":{
       "shortName":"XAX",
       "longName":"Artax",
       "network":{
          "messagePrefix":"\u0018Artax Signed Message:\n",
          "bip32":{
             "public":76067358,
             "private":76066276
          },
          "pubKeyHash":23,
          "scriptHash":7357,
          "wif":151
       },
       "coinNumber":219
    },
    "XBC":{
       "shortName":"XBC",
       "longName":"Bitcoinplus",
       "network":{
          "messagePrefix":"\u0018BitcoinPlus Signed Message:\n",
          "bip32":{
             "public":76067358,
             "private":76066276
          },
          "pubKeyHash":25,
          "scriptHash":8,
          "wif":153
       },
       "coinNumber":65
    },
    "XLM":{
       "shortName":"XLM",
       "longName":"Stellar",
       "network":"dummyNetwork",
       "coinNumber":148
    },
    "XMY":{
       "shortName":"XMY",
       "longName":"Myriadcoin",
       "network":{
          "messagePrefix":"unused",
          "bip32":{
             "public":76067358,
             "private":76066276
          },
          "pubKeyHash":50,
          "scriptHash":9,
          "wif":178
       },
       "coinNumber":90
    },
    "XRP":{
       "shortName":"XRP",
       "longName":"Ripple",
       "network":{
          "messagePrefix":"\u0018Bitcoin Signed Message:\n",
          "bech32":"bc",
          "bip32":{
             "public":76067358,
             "private":76066276
          },
          "pubKeyHash":0,
          "scriptHash":5,
          "wif":128
       },
       "coinNumber":144
    },
    "XVC":{
       "shortName":"XVC",
       "longName":"Vcash",
       "network":{
          "messagePrefix":"\u0018Vcash Signed Message:\n",
          "bip32":{
             "public":76067358,
             "private":76066276
          },
          "pubKeyHash":71,
          "scriptHash":8,
          "wif":199
       },
       "coinNumber":127
    },
    "XVG":{
       "shortName":"XVG",
       "longName":"Verge",
       "network":{
          "messagePrefix":"\u0018VERGE Signed Message:\n",
          "bip32":{
             "public":76067358,
             "private":76066276
          },
          "pubKeyHash":30,
          "scriptHash":33,
          "wif":158
       },
       "coinNumber":77
    },
    "XUEZ":{
       "shortName":"XUEZ",
       "longName":"Xuez",
       "segwitAvailable":false,
       "network":{
          "messagePrefix":"unused",
          "bip32":{
             "public":36513075,
             "private":35729707
          },
          "pubKeyHash":75,
          "scriptHash":18,
          "wif":212
       },
       "coinNumber":225
    },
    "XWC":{
       "shortName":"XWC",
       "longName":"Whitecoin",
       "network":{
          "messagePrefix":"\u0018Whitecoin Signed Message:\n",
          "bip32":{
             "public":76054302,
             "private":76059885
          },
          "pubKeyHash":73,
          "scriptHash":87,
          "wif":201
       },
       "coinNumber":155
    },
    "XZC":{
       "shortName":"XZC",
       "longName":"Zcoin (rebranded to Firo)",
       "network":{
          "messagePrefix":"\u0018Zcoin Signed Message:\n",
          "bip32":{
             "public":76067358,
             "private":76066276
          },
          "pubKeyHash":82,
          "scriptHash":7,
          "wif":210
       },
       "coinNumber":136
    },
    "ZCL":{
       "shortName":"ZCL",
       "longName":"Zclassic",
       "network":{
          "messagePrefix":"\u0018Zcash Signed Message:\n",
          "bip32":{
             "public":76067358,
             "private":76066276
          },
          "pubKeyHash":7352,
          "scriptHash":7357,
          "wif":128
       },
       "coinNumber":147
    },
    "ZEC":{
       "shortName":"ZEC",
       "longName":"Zcash",
       "network":{
          "messagePrefix":"\u0018Zcash Signed Message:\n",
          "bip32":{
             "public":76067358,
             "private":76066276
          },
          "pubKeyHash":7352,
          "scriptHash":7357,
          "wif":128
       },
       "coinNumber":133
    },
    "ZEN":{
       "shortName":"ZEN",
       "longName":"Horizen",
       "network":{
          "messagePrefix":"\u0018Zcash Signed Message:\n",
          "bip32":{
             "public":76067358,
             "private":76066276
          },
          "pubKeyHash":8329,
          "scriptHash":8342,
          "wif":128
       },
       "coinNumber":121
    }
 }