module.exports = [
    {
        shortName:"AC",
        longName:"Asiacoin",
        network:"asiacoin",
        coinNumber:51
    },
    {
        shortName:"ACC",
        longName:"Adcoin",
        network:"adcoin",
        coinNumber:161
    },
    {
        shortName:"AGM",
        longName:"Argoneum",
        network:"argoneum",
        coinNumber:421
    },
    {
        shortName:"ARYA",
        longName:"Aryacoin",
        network:"aryacoin",
        coinNumber:357
    },
    {
        shortName:"AUR",
        longName:"Auroracoin",
        network:"auroracoin",
        coinNumber:85
    },
    {
        shortName:"AXE",
        longName:"Axe",
        network:"axe",
        coinNumber:4242
    },
    {
        shortName:"ANON",
        longName:"ANON",
        network:"anon",
        coinNumber:220
    },
    {
        shortName:"BOLI",
        longName:"Bolivarcoin",
        network:"bolivarcoin",
        coinNumber:278
    },
    {
        shortName:"BCA",
        longName:"Bitcoin Atom",
        network:"atom",
        coinNumber:185
    },
    {
        shortName:"BCH",
        longName:"Bitcoin Cash",
        network:"dummyNetwork",
        coinNumber:145
    },
    {
        shortName:"BEET",
        longName:"Beetlecoin",
        network:"beetlecoin",
        coinNumber:800
    },
    {
        shortName:"BELA",
        longName:"Belacoin",
        network:"belacoin",
        coinNumber:73
    },
    {
        shortName:"BLK",
        longName:"BlackCoin",
        network:"blackcoin",
        coinNumber:10
    },
    {
        shortName:"BND",
        longName:"Blocknode",
        network:"blocknode",
        coinNumber:2941
    },
    {
        shortName:"tBND",
        longName:"Blocknode Testnet",
        network:"blocknode_testnet",
        coinNumber:1
    },
    {
        shortName:"BRIT",
        longName:"Britcoin",
        network:"britcoin",
        coinNumber:70
    },
    {
        shortName:"BSD",
        longName:"Bitsend",
        network:"bitsend",
        coinNumber:91
    },
    {
        shortName:"BST",
        longName:"BlockStamp",
        network:"blockstamp",
        coinNumber:254
    },
    {
        shortName:"BTA",
        longName:"Bata",
        network:"bata",
        coinNumber:89
    },
    {
        shortName:"BTC",
        longName:"Bitcoin",
        network:"bitcoin",
        coinNumber:0
    },
    {
        shortName:"BTC",
        longName:"Bitcoin RegTest",
        network:"regtest",
        coinNumber: 1
    },
    {
        shortName:"BTC",
        longName:"Bitcoin Testnet",
        network:"testnet",
        coinNumber:1
    },
    {
        shortName:"BITG",
        longName:"Bitcoin Green",
        network:"bitcoingreen",
        coinNumber:222
    },
    {
        shortName:"BTCP",
        longName:"Bitcoin Private",
        network:"bitcoinprivate",
        coinNumber:183
    },
    {
        shortName:"BSC",
        longName:"Binance Smart Chain",
        network:"bitcoin",
        coinNumber:60
    },
    {
        shortName:"BSV",
        longName:"BitcoinSV",
        network:"bitcoinsv",
        coinNumber:236
    },
    {
        shortName:"BTCZ",
        longName:"Bitcoinz",
        network:"bitcoinz",
        coinNumber:177
    },
    {
        shortName:"BTDX",
        longName:"BitCloud",
        network:"bitcloud",
        coinNumber:218
    },
    {
        shortName:"BTG",
        longName:"Bitcoin Gold",
        network:"bgold",
        coinNumber:156
    },
    {
        shortName:"BTX",
        longName:"Bitcore",
        network:"bitcore",
        coinNumber:160
    },
    {
        shortName:"CCN",
        longName:"Cannacoin",
        network:"cannacoin",
        coinNumber:19
    },
    {
        shortName:"CESC",
        longName:"Cryptoescudo",
        network:"cannacoin",
        coinNumber:111
    },
    {
        shortName:"CDN",
        longName:"Canadaecoin",
        network:"canadaecoin",
        coinNumber:34
    },
    {
        shortName:"CLAM",
        longName:"Clams",
        network:"clam",
        coinNumber:23
    },
    {
        shortName:"CLO",
        longName:"Callisto",
        segwitAvailable: false,
        network:"bitcoin",
        coinNumber:820
    },
    {
        shortName:"CLUB",
        longName:"Clubcoin",
        network:"clubcoin",
        coinNumber:79
    },
    {
        shortName:"CMP",
        longName:"Compcoin",
        network:"compcoin",
        coinNumber:71
    },
    {
        shortName:"CPU",
        longName:"CPUchain",
        network:"cpuchain",
        coinNumber:363
    },
    {
        shortName:"CRAVE",
        longName:"Crave",
        network:"crave",
        coinNumber:186
    },
    {
        shortName:"CRP",
        longName:"CranePay",
        network:"cranepay",
        coinNumber:2304
    },

    {
        shortName:"CRW",
        longName:"Crown (Legacy)",
        network:"crown",
        coinNumber:72
    },
    {
        shortName:"CRW",
        longName:"Crown",
        network:"crown",
        coinNumber:72
    },
    {
        shortName:"CSC",
        longName:"CasinoCoin",
        network:"bitcoin",
        coinNumber:359
    },
    {
        shortName:"DASH",
        longName:"Dash",
        network:"dash",
        coinNumber:5
    },
    {
        shortName:"DASH",
        longName:"Dash Testnet",
        network:"dashtn",
        coinNumber:1
    },
    {
        shortName:"DFC",
        longName:"Defcoin",
        network:"defcoin",
        coinNumber:1337
    },
    {
        shortName:"DGB",
        longName:"Digibyte",
        network:"digibyte",
        coinNumber:20
    },
    {
        shortName:"DGC",
        longName:"Digitalcoin",
        network:"digitalcoin",
        coinNumber:18
    },
    {
        shortName:"DMD",
        longName:"Diamond",
        network:"diamond",
        coinNumber:152
    },
    {
        shortName:"DNR",
        longName:"Denarius",
        network:"denarius",
        coinNumber:116
    },
    {
        shortName:"DOGE",
        longName:"Dogecoin",
        network:"dogecoin",
        coinNumber:3
    },
    {
        shortName:"DOGEt",
        longName:"Dogecoin Testnet",
        network:"dogecointestnet",
        coinNumber:1
    },
    {
        shortName:"DXN",
        longName:"DEXON",
        network:"bitcoin",
        coinNumber:237
    },
    {
        shortName:"ECN",
        longName:"Ecoin",
        network:"ecoin",
        coinNumber:115
    },
    {
        shortName:"EDRC",
        longName:"Edrcoin",
        network:"edrcoin",
        coinNumber:56
    },
    {
        shortName:"EFL",
        longName:"Egulden",
        network:"egulden",
        coinNumber:78
    },
    {
        shortName:"ELA",
        longName:"Elastos",
        network:"elastos",
        coinNumber:2305
    },
    {
        shortName:"ELLA",
        longName:"Ellaism",
        segwitAvailable: false,
        network:"bitcoin",
        coinNumber:163
    },
    {
        shortName:"EMC2",
        longName:"Einsteinium",
        network:"einsteinium",
        coinNumber:41
    },
    {
        shortName:"ERC",
        longName:"Europecoin",
        network:"europecoin",
        coinNumber:151
    },
    {
        shortName:"EOS",
        longName:"EOSIO",
        network:"bitcoin",
        coinNumber:194
    },
    {
        shortName:"ERE",
        longName:"EtherCore",
        segwitAvailable: false,
        network:"bitcoin",
        coinNumber:466
    },
    {
        shortName:"ESN",
        longName:"Ethersocial Network",
        segwitAvailable: false,
        network:"bitcoin",
        coinNumber:31102
    },
    {
        shortName:"ETC",
        longName:"Ethereum Classic",
        segwitAvailable: false,
        network: "bitcoin",
        coinNumber:61
    },
    {
        shortName:"ETH",
        longName:"Ethereum",
        network: "bitcoin",
        coinNumber:60
    },
    {
        shortName:"EWT",
        longName:"EnergyWeb",
        network:"bitcoin",
        coinNumber:246
    },
    {
        shortName:"EXCL",
        longName:"Exclusivecoin",
        network:"exclusivecoin",
        coinNumber:190
    },
    {
        shortName:"EXCC",
        longName:"ExchangeCoin",
        network:"exchangecoin",
        coinNumber:0
    },
    {
        shortName:"EXP",
        longName:"Expanse",
        segwitAvailable: false,
        network:"bitcoin",
        coinNumber:40
    },
    {
        shortName:"FIO",
        longName:"Foundation for Interwallet Operability",
        network:"bitcoin",
        coinNumber:235
    },
    {
        shortName:"FIRO",
        longName:"Firo (Zcoin rebrand)",
        network:"firo",
        coinNumber:136
    },
    {
        shortName:"FIX",
        longName:"FIX",
        network:"fix",
        coinNumber:336
    },
    {
        shortName:"FIX",
        longName:"FIX Testnet",
        network:"fixtestnet",
        coinNumber:1
    },
    {
        shortName:"FJC",
        longName:"Fujicoin",
        network:"fujicoin",
        coinNumber:75
    },
    {
        shortName:"FLASH",
        longName:"Flashcoin",
        network:"flashcoin",
        coinNumber:120
    },
    {
        shortName:"FRST",
        longName:"Firstcoin",
        network:"firstcoin",
        coinNumber:167
    },
    {
        shortName:"FTC",
        longName:"Feathercoin",
        network:"feathercoin",
        coinNumber:8
    },
    {
        shortName:"GAME",
        longName:"GameCredits",
        network:"game",
        coinNumber:101
    },
    {
        shortName:"GBX",
        longName:"Gobyte",
        network:"gobyte",
        coinNumber:176
    },
    {
        shortName:"GCR",
        longName:"GCRCoin",
        network:"gcr",
        coinNumber:79
    },
    {
        shortName:"GRC",
        longName:"Gridcoin",
        network:"gridcoin",
        coinNumber:84
    },
    {
        shortName:"GRS",
        longName:"Groestlcoin",
        network:"groestlcoin",
        coinNumber:17
    },
    {
        shortName:"GRS",
        longName:"Groestlcoin Testnet",
        network:"groestlcointestnet",
        coinNumber:1
    },
    {
        shortName:"HNS",
        longName:"Handshake",
        coinNumber:5353
    },
    {
        shortName:"HNC",
        longName:"Helleniccoin",
        network:"helleniccoin",
        coinNumber:168
    },
    {
        shortName:"HUSH",
        longName:"Hush (Legacy)",
        network:"hush",
        coinNumber:197
    },
    {
        shortName:"HUSH",
        longName:"Hush3",
        network:"hush3",
        coinNumber:197
    },
    {
        shortName:"INSN",
        longName:"Insane",
        network:"insane",
        coinNumber:68
    },
    {
        shortName:"IOP",
        longName:"Iop",
        network:"iop",
        coinNumber:66
    },
    {
        shortName:"IXC",
        longName:"Ixcoin",
        network:"ixcoin",
        coinNumber:86
    },
    {
        shortName:"JBS",
        longName:"Jumbucks",
        network:"jumbucks",
        coinNumber:26
    },
    {
        shortName:"KMD",
        longName:"Komodo",
        bip49available: false,
        network:"komodo",
        coinNumber:141
    },
    {
        shortName:"KOBO",
        longName:"Kobocoin",
        bip49available: false,
        network:"kobocoin",
        coinNumber:196
    },
    {
        shortName:"LBC",
        longName:"Library Credits",
        network:"lbry",
        coinNumber:140
    },
    {
        shortName:"LCC",
        longName:"Litecoincash",
        network:"litecoincash",
        coinNumber:192
    },
    {
        shortName:"LDCN",
        longName:"Landcoin",
        network:"landcoin",
        coinNumber:63
    },
    {
        shortName:"LINX",
        longName:"Linx",
        network:"linx",
        coinNumber:114
    },
    {
        shortName:"LKR",
        longName:"Lkrcoin",
        segwitAvailable: false,
        network:"lkrcoin",
        coinNumber:557
    },
    {
        shortName:"LTC",
        longName:"Litecoin",
        network:"litecoin",
        coinNumber:2
    },
    {
        shortName:"LTCt",
        longName:"Litecoin Testnet",
        network:"litecointestnet",
        coinNumber:1
    },
    {
        shortName:"LTZ",
        longName:"LitecoinZ",
        network:"litecoinz",
        coinNumber:221
    },
    {
        shortName:"LYNX",
        longName:"Lynx",
        network:"lynx",
        coinNumber:191
    },
    {
        shortName:"MAZA",
        longName:"Maza",
        network:"maza",
        coinNumber:13
    },
    {
        shortName:"MEC",
        longName:"Megacoin",
        network:"megacoin",
        coinNumber:217
    },
    {
        shortName:"MIX",
        longName:"MIX",
        segwitAvailable: false,
        network:"bitcoin",
        coinNumber:76
    },
    {
        shortName:"MNX",
        longName:"Minexcoin",
        network:"minexcoin",
        coinNumber:182
    },
    {
        shortName:"MONA",
        longName:"Monacoin",
        network:"monacoin",
        coinNumber:22
    },
    {
        shortName:"MONK",
        longName:"Monkey Project",
        network:"monkeyproject",
        coinNumber:214
    },
    {
        shortName:"MOAC",
        longName:"MOAC",
        segwitAvailable: false,
        network:"bitcoin",
        coinNumber:314
    },
    {
        shortName:"MUSIC",
        longName:"Musicoin",
        segwitAvailable: false,
        network:"bitcoin",
        coinNumber:184
    },
    {
        shortName:"NANO",
        longName:"Nano",
        network:"dummyNetwork", 
        coinNumber:165
    },
    {
        shortName:"NAV",
        longName:"Navcoin",
        network:"navcoin",
        coinNumber:130
    },
    {
        shortName:"NAS",
        longName:"Nebulas",
        network:"bitcoin",
        coinNumber:2718
    },
    {
        shortName:"NEBL",
        longName:"Neblio",
        network:"neblio",
        coinNumber:146
    },
    {
        shortName:"NEOS",
        longName:"Neoscoin",
        network:"neoscoin",
        coinNumber:25
    },
    {
        shortName:"NIX",
        longName:"NIX Platform",
        network:"nix",
        coinNumber:400
    },
    {
        shortName:"NLG",
        longName:"Gulden",
        network:"gulden",
        coinNumber:87
    },
    {
        shortName:"NMC",
        longName:"Namecoin",
        network:"namecoin",
        coinNumber:7
    },
    {
        shortName:"NRG",
        longName:"Energi",
        network:"energi",
        coinNumber:204
    },
    {
        shortName:"NRO",
        longName:"Neurocoin",
        network:"neurocoin",
        coinNumber:110
    },
    {
        shortName:"NSR",
        longName:"Nushares",
        network:"nushares",
        coinNumber:11
    },
    {
        shortName:"NYC",
        longName:"Newyorkc",
        network:"newyorkc",
        coinNumber:179
    },
    {
        shortName:"NVC",
        longName:"Novacoin",
        network:"novacoin",
        coinNumber:50
    },
    {
        shortName:"OK",
        longName:"Okcash",
        network:"okcash",
        coinNumber:69
    },
    {
        shortName:"OMNI",
        longName:"Omnicore",
        network:"omnicore",
        coinNumber:200
    },
    {
        shortName:"ONION",
        longName:"DeepOnion",
        network:"deeponion",
        coinNumber:305
    },
    {
        shortName:"ONX",
        longName:"Onixcoin",
        network:"onixcoin",
        coinNumber:174
    },
    {
        shortName:"PHR",
        longName:"Phore",
        network:"phore",
        coinNumber:444
    },
    {
        shortName:"PINK",
        longName:"Pinkcoin",
        network:"pinkcoin",
        coinNumber:117
    },
    {
        shortName:"PIRL",
        longName:"Pirl",
        segwitAvailable: false,
        network:"bitcoin",
        coinNumber:164
    },
    {
        shortName:"PIVX",
        longName:"PIVX",
        network:"pivx",
        coinNumber:119
    },
    {
        shortName:"PIVX",
        longName:"PIVX Testnet",
        network:"pivxtestnet",
        coinNumber:1
    },
    {
        shortName:"POA",
        longName:"Poa",
        segwitAvailable: false,
        network:"bitcoin",
        coinNumber:178
    },
    {
        shortName:"POSW",
        longName:"POSWcoin",
        network:"poswcoin",
        coinNumber:47
    },
    {
        shortName:"POT",
        longName:"Potcoin",
        network:"potcoin",
        coinNumber:81
    },
    {
        shortName:"PPC",
        longName:"Peercoin",
        network:"peercoin",
        coinNumber:6
    },
    {
        shortName:"PRJ",
        longName:"ProjectCoin",
        network:"projectcoin",
        coinNumber:533
    },
    {
        shortName:"PSB",
        longName:"Pesobit",
        network:"pesobit",
        coinNumber:62
    },
    {
        shortName:"PUT",
        longName:"Putincoin",
        network:"putincoin",
        coinNumber:122
    },
    {
        shortName:"RPD",
        longName:"Rapids",
        network:"rapids",
        coinNumber:320
    },
    {
        shortName:"RVN",
        longName:"Ravencoin",
        network:"ravencoin",
        coinNumber:175
    },
    {
        shortName:"R-BTC",
        longName:"RSK",
        network:"rsk",
        coinNumber:137
    },
    {
        shortName:"tR-BTC",
        longName:"RSK Testnet",
        network:"rsktestnet",
        coinNumber:37310
    },
    {
        shortName:"RBY",
        longName:"Rubycoin",
        network:"rubycoin",
        coinNumber:16
    },
    {
        shortName:"RDD",
        longName:"Reddcoin",
        network:"reddcoin",
        coinNumber:4
    },
    {
        shortName:"RVR",
        longName:"RevolutionVR",
        network:"revolutionvr",
        coinNumber:129
    },
    {
        shortName:"SAFE",
        longName:"Safecoin",
        network:"safecoin",
        coinNumber:19165
    },
    {
        shortName:"SCRIBE",
        longName:"Scribe",
        network:"scribe",
        coinNumber:545
    },
    {
        shortName:"SLS",
        longName:"Salus",
        network:"salus",
        coinNumber:63
    },
    {
        shortName:"SDC",
        longName:"ShadowCash",
        network:"shadow",
        coinNumber:35
    },
    {
        shortName:"SDC",
        longName:"ShadowCash Testnet",
        network:"shadowtn",
        coinNumber:1
    },
    {
        shortName:"SLM",
        longName:"Slimcoin",
        network:"slimcoin",
        coinNumber:63
    },
    {
        shortName:"SLM",
        longName:"Slimcoin Testnet",
        network:"slimcointn",
        coinNumber:111
    },
    {
        shortName:"SLP",
        longName:"Simple Ledger Protocol",
        network:"dummyNetwork",
        coinNumber:245
    },
    {
        shortName:"SLR",
        longName:"Solarcoin",
        network:"solarcoin",
        coinNumber:58
    },
    {
        shortName:"SMLY",
        longName:"Smileycoin",
        network:"smileycoin",
        coinNumber:59
    },
    {
        shortName:"STASH",
        longName:"Stash",
        network:"stash",
        coinNumber:0xC0C0
    },
    {
        shortName:"STASH",
        longName:"Stash Testnet",
        network:"stashtn",
        coinNumber:0xCAFE
    },
    {
        shortName:"STRAT",
        longName:"Stratis",
        network:"stratis",
        coinNumber:105
    },
    {
        shortName:"SUGAR",
        longName:"Sugarchain",
        network:"sugarchain",
        coinNumber:408
    },
    {
        shortName:"TUGAR",
        longName:"Sugarchain Testnet",
        network:"sugarchaintestnet",
        coinNumber:408
    },
    {
        shortName:"SWTC",
        longName:"Jingtum",
        network:"bitcoin",
        coinNumber:315
    },
    {
        shortName:"TSTRAT",
        longName:"Stratis Testnet",
        network:"stratistest",
        coinNumber:105
    },
    {
        shortName:"SYS",
        longName:"Syscoin",
        network:"syscoin",
        coinNumber:57
    },
    {
        shortName:"THC",
        longName:"Hempcoin",
        network:"hempcoin",
        coinNumber:113
    },
    {
        shortName:"THT",
        longName:"Thought",
        network:"thought",
        coinNumber:1618
    },
    {
        shortName:"TOA",
        longName:"Toa",
        network:"toa",
        coinNumber:159
    },
    {
        shortName:"TRX",
        longName:"Tron",
        network:"dummyNetwork",
        coinNumver:195
    },
    {
        shortName:"TWINS",
        longName:"TWINS",
        network:"twins",
        coinNumber:970
    },
    {
        shortName:"TWINS",
        longName:"TWINS Testnet",
        network:"twinstestnet",
        coinNumber:1
    },
    {
        shortName:"USC",
        longName:"Ultimatesecurecash",
        network:"ultimatesecurecash",
        coinNumber:112
    },
    {
        shortName:"USNBT",
        longName:"NuBits",
        network:"nubits",
        coinNumber:12
    },
    {
        shortName:"UNO",
        longName:"Unobtanium",
        network:"unobtanium",
        coinNumber:92
    },
    {
        shortName:"VASH",
        longName:"Vpncoin",
        network:"vpncoin",
        coinNumber:33
    },
    {
        shortName:"VET",
        longName:"VeChain",
        network:"bitcoin",
        coinNumber:818
    },
    {
        shortName:"VIA",
        longName:"Viacoin",
        network:"viacoin",
        coinNumber:14
    },
    {
        shortName:"VIA",
        longName:"Viacoin Testnet",
        network:"viacointestnet",
        coinNumber:1
    },
    {
        shortName:"VIVO",
        longName:"Vivo",
        network:"vivo",
        coinNumber:166
    },
    {
        shortName:"VTC",
        longName:"Vertcoin",
        network:"vertcoin",
        coinNumber:28
    },
    {
        shortName:"WGR",
        longName:"Wagerr",
        network:"wagerr",
        coinNumber:7825266
    },
    {
        shortName:"WC",
        longName:"Wincoin",
        network:"wincoin",
        coinNumber:181
    },
    {
        shortName:"XAX",
        longName:"Artax",
        network:"artax",
        coinNumber:219
    },
    {
        shortName:"XBC",
        longName:"Bitcoinplus",
        network:"bitcoinplus",
        coinNumber:65
    },
    {
        shortName:"XLM",
        longName:"Stellar",
        network:"dummyNetwork",
        coinNumber:148
    },
    {
        shortName:"XMY",
        longName:"Myriadcoin",
        network:"myriadcoin",
        coinNumber:90
    },
    {
        shortName:"XRP",
        longName:"Ripple",
        network:"bitcoin",
        coinNumber:144
    },
    {
        shortName:"XVC",
        longName:"Vcash",
        network:"vcash",
        coinNumber:127
    },
    {
        shortName:"XVG",
        longName:"Verge",
        network:"verge",
        coinNumber:77
    },
    {
        shortName:"XUEZ",
        longName:"Xuez",
        segwitAvailable: false,
        network:"xuez",
        coinNumber:225
    },
    {
        shortName:"XWC",
        longName:"Whitecoin",
        network:"whitecoin",
        coinNumber:155
    },
    {
        shortName:"XZC",
        longName:"Zcoin (rebranded to Firo)",
        network:"zcoin",
        coinNumber:136
    },
    {
        shortName:"ZCL",
        longName:"Zclassic",
        network:"zclassic",
        coinNumber:147
    },
    {
        shortName:"ZEC",
        longName:"Zcash",
        network:"zcash",
        coinNumber:133
    },
    {
        shortName:"ZEN",
        longName:"Horizen",
        network:"zencash",
        coinNumber:121
    },
]